-- Fix contact-company associations
-- This script updates contacts to link them to their proper companies

-- Update each contact with their company based on the original Excel mappings
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Advocating Change Together (ACT)' AND organization_id = 7 LIMIT 1) WHERE email = 'act@selfadvocacy.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'American Indian Family Center' AND organization_id = 7 LIMIT 1) WHERE email = 'kristin.kinney@AIFCmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'American Indian OIC' AND organization_id = 7 LIMIT 1) WHERE email = 'KatieF@AIOIC.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Ampersand Families' AND organization_id = 7 LIMIT 1) WHERE email = 'christina@ampersandfamilies.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Annex Teen Clinic' AND organization_id = 7 LIMIT 1) WHERE email = 'holly@annexteenclinic.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Aqwalife' AND organization_id = 7 LIMIT 1) WHERE email = 'Alexis@Aqwalife.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Ausherman Family Foundation' AND organization_id = 7 LIMIT 1) WHERE email = 'LAdams@Ausherman.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Avenues for Youth' AND organization_id = 7 LIMIT 1) WHERE email = 'kmeerse@avenuesforyouth.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'The Beacon' AND organization_id = 7 LIMIT 1) WHERE email = 'director@thebeacondm.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Belle Plaine Food Shelf' AND organization_id = 7 LIMIT 1) WHERE email = 'ptollie@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Bellis' AND organization_id = 7 LIMIT 1) WHERE email = 'info@mybellis.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Beyond New Beginnings' AND organization_id = 7 LIMIT 1) WHERE email = 'molly@beyondnewbeginnings.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Breakthrough Twin Cities' AND organization_id = 7 LIMIT 1) WHERE email = 'jreimnitz@breakthroughtwincities.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Bridge for Youth' AND organization_id = 7 LIMIT 1) WHERE email = 'l.mears@bridgeforyouth.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Bridges of Hope' AND organization_id = 7 LIMIT 1) WHERE email = 'info@bridgesofhopebrainerd.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'CADA' AND organization_id = 7 LIMIT 1) WHERE email = 'brittanyw@cadamn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'CAER Food Shelf' AND organization_id = 7 LIMIT 1) WHERE email = 'heather.kliewer@caerfoodshelf.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Camp Omega' AND organization_id = 7 LIMIT 1) WHERE email = 'Bob@CampOmega.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'CAPI' AND organization_id = 7 LIMIT 1) WHERE email = 'mary.niedermeyer@capiusa.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Carver County Historical Society' AND organization_id = 7 LIMIT 1) WHERE email = 'wbiorn@carvercountymn.gov' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Communnity Emergency Assistance Program (CEAP)' AND organization_id = 7 LIMIT 1) WHERE email = 'clare.brumback@ceap.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Center for Coaching in Organizations' AND organization_id = 7 LIMIT 1) WHERE email = 'curtgray33@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Central Minnesota Mental Health Center' AND organization_id = 7 LIMIT 1) WHERE email = 'jbrandon@cmmhc.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Century College Foundation' AND organization_id = 7 LIMIT 1) WHERE email = 'nora.slawik@century.edu' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Child Care Aware' AND organization_id = 7 LIMIT 1) WHERE email = 'DavidH@childcareawaremn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Children''s Hospital Association' AND organization_id = 7 LIMIT 1) WHERE email = 'sarah.driever@childrensmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'College Possible' AND organization_id = 7 LIMIT 1) WHERE email = 'hr@collegepossible.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'CommonBond Communities' AND organization_id = 7 LIMIT 1) WHERE email = 'Deidre.Schmidt@commonbond.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Accord' AND organization_id = 7 LIMIT 1) WHERE email = 'executive.director@accordstpaul.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Community Thread' AND organization_id = 7 LIMIT 1) WHERE email = 'ExecutiveDirector@CommunityThread.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Conservation Corps Minnesota and Iowa' AND organization_id = 7 LIMIT 1) WHERE email = 'Nalani.mccutcheon@conservationcorps.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Corner House' AND organization_id = 7 LIMIT 1) WHERE email = 'Christy@CornerHouseMN.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Customized Options' AND organization_id = 7 LIMIT 1) WHERE email = 'customizedoptions@hotmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Dakota Woodlands' AND organization_id = 7 LIMIT 1) WHERE email = 'Colleena@dakotawoodlands.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'DARTS' AND organization_id = 7 LIMIT 1) WHERE email = 'mike.lavin@Darts1.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'DepartSmart' AND organization_id = 7 LIMIT 1) WHERE email = 'sheryl@departsmart.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'DuNord Foundation' AND organization_id = 7 LIMIT 1) WHERE email = 'info@dunordfoundation.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Emerge' AND organization_id = 7 LIMIT 1) WHERE email = 'wynnem@emerge-mn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Epilepsy Foundation of Minnesota' AND organization_id = 7 LIMIT 1) WHERE email = 'jenna.carter@efmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'EVOLVE Family Services' AND organization_id = 7 LIMIT 1) WHERE email = 'sbarnes@evolveservices.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Face 2 Face' AND organization_id = 7 LIMIT 1) WHERE email = 'getachew-kreusserh@face2face.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Family Child Development Center' AND organization_id = 7 LIMIT 1) WHERE email = 'Info@fcdc.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Feed Iowa First' AND organization_id = 7 LIMIT 1) WHERE email = 'jody@feediowa1st.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Feline Rescue, Inc.' AND organization_id = 7 LIMIT 1) WHERE email = 'kate.king@felinerescue.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Foundations for Essential Needs' AND organization_id = 7 LIMIT 1) WHERE email = 'kateburggraff@ffen.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Friends in Need Food Shelf' AND organization_id = 7 LIMIT 1) WHERE email = 'director@finfood.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Friends of Willow River and Kinnickinnic State Parks' AND organization_id = 7 LIMIT 1) WHERE email = 'rthofern@willowkinnifriends.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Great Expectations School' AND organization_id = 7 LIMIT 1) WHERE email = 'rachel.lehman@greatexpectationsschool.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Green Card Voices' AND organization_id = 7 LIMIT 1) WHERE email = 'Aaliyah@GreenCardVoices.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'H2O For Life' AND organization_id = 7 LIMIT 1) WHERE email = 'Doug@H2OforLifeSchools.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Handy Help LLC' AND organization_id = 7 LIMIT 1) WHERE email = 'phia.xiong@handyhelpllc.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Haven House' AND organization_id = 7 LIMIT 1) WHERE email = 'jenna@havenhouse.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Hawthorne Neighborhood Council' AND organization_id = 7 LIMIT 1) WHERE email = 'dhawkins@hncmpls.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'History Theatre' AND organization_id = 7 LIMIT 1) WHERE email = 'Kmueller@HistoryTheatre.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Hmong Cultural Center' AND organization_id = 7 LIMIT 1) WHERE email = 'txong@hmongcc.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'HOPE 4 Youth' AND organization_id = 7 LIMIT 1) WHERE email = 'lwilliams@hope4youthmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'HOPE Coalition' AND organization_id = 7 LIMIT 1) WHERE email = 'info@hope-coalition.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Hope House' AND organization_id = 7 LIMIT 1) WHERE email = 'dan.pfarr@180degreed.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'ICA Food Shelf' AND organization_id = 7 LIMIT 1) WHERE email = 'Dan@ICAFoodShelf.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Interfaith Outreach & Community Partners' AND organization_id = 7 LIMIT 1) WHERE email = 'executivedirector@iocp.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Irish Fair of Minnesota' AND organization_id = 7 LIMIT 1) WHERE email = 'info@irishfair.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Jewish Family and Children''s Services' AND organization_id = 7 LIMIT 1) WHERE email = 'jhalper@jfcsmpls.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Jewish Programming and Housing (J-HAP)' AND organization_id = 7 LIMIT 1) WHERE email = 'info@j-hap.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Joint Religious Legislative Coalition' AND organization_id = 7 LIMIT 1) WHERE email = 'leah@jrlc.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Lakeshore Payers' AND organization_id = 7 LIMIT 1) WHERE email = 'office@lakeshoreplayers.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'LDA Minnesota' AND organization_id = 7 LIMIT 1) WHERE email = 'mm@ldaminnesota.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Legal Services of North Dakota' AND organization_id = 7 LIMIT 1) WHERE email = 'jlee@legalassist.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Listen Up Youth Radio' AND organization_id = 7 LIMIT 1) WHERE email = 'contact@listenupyouthradio.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Literacy Minnesota' AND organization_id = 7 LIMIT 1) WHERE email = 'RaviKrishnan93@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Friends & Co' AND organization_id = 7 LIMIT 1) WHERE email = 'jfalvey@friendsco.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Little Free Library' AND organization_id = 7 LIMIT 1) WHERE email = 'dgumnit@littlefreelibrary.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Love Inc.' AND organization_id = 7 LIMIT 1) WHERE email = 'anorby@loveinccc.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Lutheran Island Camp' AND organization_id = 7 LIMIT 1) WHERE email = 'licdirector@islandcamp.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Metropolitan Alliance of Connected Communities (MACC)' AND organization_id = 7 LIMIT 1) WHERE email = 'steven.houtz@macc-mn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Manna Market' AND organization_id = 7 LIMIT 1) WHERE email = 'ngregory@youthwayministries.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Metropolitan Center for Independent Living (MCIL)' AND organization_id = 7 LIMIT 1) WHERE email = 'jessebg@mcil-mn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'McLeod Emergency Food Shelf' AND organization_id = 7 LIMIT 1) WHERE email = 'carrie@mcleodfs.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MELSA' AND organization_id = 7 LIMIT 1) WHERE email = 'sherry@melsa.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Merrick Community Services' AND organization_id = 7 LIMIT 1) WHERE email = 'drodriguez@merrickcs.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Midwest Reliability Organization' AND organization_id = 7 LIMIT 1) WHERE email = 'Sara.Patrick@mro.net' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Midwest Special Services' AND organization_id = 7 LIMIT 1) WHERE email = 'jjohnson@mssmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Milestone' AND organization_id = 7 LIMIT 1) WHERE email = 'jshreifels@milestone.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Minneapolis Farmers Market' AND organization_id = 7 LIMIT 1) WHERE email = 'MplsFarmersMarket@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Minnesota Housing Partnership (MHP)' AND organization_id = 7 LIMIT 1) WHERE email = 'anne.mavity@mhponline.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Minnesota Parks and Recreation Foundation' AND organization_id = 7 LIMIT 1) WHERE email = 'Jennifer.Fink@newbrightonmn.gov' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN Black Chamber of Commerce' AND organization_id = 7 LIMIT 1) WHERE email = 'info@minnesotablackchamber.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN China Friendship Garden Society' AND organization_id = 7 LIMIT 1) WHERE email = 'RomiSlowiak@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN Community Education Association' AND organization_id = 7 LIMIT 1) WHERE email = 'mdickhausen@mn-mcea.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN Community Health Workers Alliance' AND organization_id = 7 LIMIT 1) WHERE email = 'ATGainey@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN HomeCare Association' AND organization_id = 7 LIMIT 1) WHERE email = 'kmesserli@mnhomecare.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN Metro North Tourism' AND organization_id = 7 LIMIT 1) WHERE email = 'al@tcgateway.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN School Bus Operators Association' AND organization_id = 7 LIMIT 1) WHERE email = 'info@msboa.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN State Fire Chiefs Association' AND organization_id = 7 LIMIT 1) WHERE email = 'sandy@msfca.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN Youth Ski League' AND organization_id = 7 LIMIT 1) WHERE email = 'amy@mski.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MNRAAA' AND organization_id = 7 LIMIT 1) WHERE email = 'Jswanson@MNRAAA.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MoveFwd Minnesota' AND organization_id = 7 LIMIT 1) WHERE email = 'email@movefwd.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'MN Subcontractors Association' AND organization_id = 7 LIMIT 1) WHERE email = 'info@msamn.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'NAEHCY' AND organization_id = 7 LIMIT 1) WHERE email = 'dnichol-son@naehcy.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'National Association of Social Workers' AND organization_id = 7 LIMIT 1) WHERE email = 'kgoodenough@socialworkers.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Neighbors, Inc.' AND organization_id = 7 LIMIT 1) WHERE email = 'dawn@neighborsmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'North St. Paul Area Food Shelf' AND organization_id = 7 LIMIT 1) WHERE email = 'nspfs@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Northeast Contemporary Services, Inc.' AND organization_id = 7 LIMIT 1) WHERE email = 'jennifer.freeburg@NCSIdaysupports.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Oasis for Youth' AND organization_id = 7 LIMIT 1) WHERE email = 'jnelson@oasisforyouth.oth' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Onward Eden Prairie' AND organization_id = 7 LIMIT 1) WHERE email = 'tricia@onwardep.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Open Cupboard' AND organization_id = 7 LIMIT 1) WHERE email = 'jessica@opencupboard.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Open Doors for Youth' AND organization_id = 7 LIMIT 1) WHERE email = 'cindyl.opendoors@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Our Neighbor''s Place' AND organization_id = 7 LIMIT 1) WHERE email = 'shelly.smith@ourneighborsplace.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Phoenix Alternative, Inc.(PAI)' AND organization_id = 7 LIMIT 1) WHERE email = 'mminer@paimn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Partnership Resources, Inc.' AND organization_id = 7 LIMIT 1) WHERE email = 'julie@partnershipresources.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Pathway Health Services' AND organization_id = 7 LIMIT 1) WHERE email = 'consult@pathwayhealth.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Phoenix Residence' AND organization_id = 7 LIMIT 1) WHERE email = 'dscott@phoenixresidence.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Portable Sanitation Association International' AND organization_id = 7 LIMIT 1) WHERE email = 'veronicac@PSAI.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Preservation Alliance' AND organization_id = 7 LIMIT 1) WHERE email = 'paul@preservationalliance.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'PRISM' AND organization_id = 7 LIMIT 1) WHERE email = 'mness@prismmpls.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Project Pathfinder' AND organization_id = 7 LIMIT 1) WHERE email = 'kholgren@projectpathfinder.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Public Arts St. Paul' AND organization_id = 7 LIMIT 1) WHERE email = 'mohannad@publicartsstpaul.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Ramsey County Workforce Solutions' AND organization_id = 7 LIMIT 1) WHERE email = 'michelle.belitz@CO.RAMSEY.MN.US' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Relate Counseling Center' AND organization_id = 7 LIMIT 1) WHERE email = 'jtwiton@relatemn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Resource West' AND organization_id = 7 LIMIT 1) WHERE email = 'tracie@resourcewest.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Ridgeview Senior Apartments' AND organization_id = 7 LIMIT 1) WHERE email = 'Moriak.Ent@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Rural Renewable Energy Alliance (RREAL)' AND organization_id = 7 LIMIT 1) WHERE email = 'info@rreal.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Seward Community Co-Op' AND organization_id = 7 LIMIT 1) WHERE email = 'tabitha@seward.coop' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Sibley County FoodShare' AND organization_id = 7 LIMIT 1) WHERE email = 'sibleycountyfoodshare@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Solid Ground' AND organization_id = 7 LIMIT 1) WHERE email = 'Dhunter@solidgroundmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Southeast Minnesota Area Agency on Aging' AND organization_id = 7 LIMIT 1) WHERE email = 'laurie@semaaa.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Southside Services I. INC.' AND organization_id = 7 LIMIT 1) WHERE email = 'josh@southsideservices.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'St. Paul Community Literacy Consortium' AND organization_id = 7 LIMIT 1) WHERE email = 'kara.schommer@gmail.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'St. Paul Conservatory of Music' AND organization_id = 7 LIMIT 1) WHERE email = 'mary@thespcm.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Agate Housing and Services' AND organization_id = 7 LIMIT 1) WHERE email = 'Kyle.Hanson@agatemn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Start Early Funders Coalition' AND organization_id = 7 LIMIT 1) WHERE email = 'carrie@startearlyfunders.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'START Senior Solutions' AND organization_id = 7 LIMIT 1) WHERE email = 'tracy@startseniorsolutions.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Steve Rummler Hope Network' AND organization_id = 7 LIMIT 1) WHERE email = 'ahouse@rummlerHOPE.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Stillwater Public Library Foundation' AND organization_id = 7 LIMIT 1) WHERE email = 'splf@stillwaterlibraryfoundation.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Tanager Place' AND organization_id = 7 LIMIT 1) WHERE email = 'orice@tanagerplace.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Trellis' AND organization_id = 7 LIMIT 1) WHERE email = 'dsimonsen@trellisconnects.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Tasks Unlimited' AND organization_id = 7 LIMIT 1) WHERE email = 'info@tasksunlimited.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'The Isthmus Foundation' AND organization_id = 7 LIMIT 1) WHERE email = 'isthmusfoundation.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'The Lift Garage' AND organization_id = 7 LIMIT 1) WHERE email = 'cathy@theliftgarage.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'The Link' AND organization_id = 7 LIMIT 1) WHERE email = 'bholger@thelinkmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'The Partnership Plan' AND organization_id = 7 LIMIT 1) WHERE email = 'robbinsr@partnershipplan.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'The Periphery Foundation' AND organization_id = 7 LIMIT 1) WHERE email = 'brandon@theperiphery.com' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Think Small' AND organization_id = 7 LIMIT 1) WHERE email = 'info@thinksmall.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Move Minnesota' AND organization_id = 7 LIMIT 1) WHERE email = 'mjc@movemn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'US Math Recovery Council' AND organization_id = 7 LIMIT 1) WHERE email = 'christina@mathrecovery.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'Veteran Resilience Project' AND organization_id = 7 LIMIT 1) WHERE email = 'jonna@veteranresilience.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'White Bear Lake Area Historical Society' AND organization_id = 7 LIMIT 1) WHERE email = 'office@whitebearhistory.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'YouthLink' AND organization_id = 7 LIMIT 1) WHERE email = 'rmelzer@youthlinkmn.org' AND organization_id = 7;
UPDATE contacts SET company_id = (SELECT id FROM companies WHERE name = 'White Bear Area Food Shelf' AND organization_id = 7 LIMIT 1) WHERE email = 'perry@whitebearfoodshelf.org' AND organization_id = 7;

-- Verify the updates
SELECT COUNT(*) as contacts_with_companies
FROM contacts 
WHERE organization_id = 7 
AND company_id IS NOT NULL;

SELECT COUNT(*) as contacts_without_companies
FROM contacts 
WHERE organization_id = 7 
AND company_id IS NULL;