-- Insert Contacts (run this after companies are inserted)
-- Note: contacts table doesn't have created_by_id, but has owner_id
INSERT INTO contacts (
    first_name, last_name, email, company_id,
    organization_id, created_at, updated_at
) VALUES
('Jen', 'Walton', 'act@selfadvocacy.org', (SELECT id FROM companies WHERE name = 'Advocating Change Together (ACT)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kristin', 'Kinney', 'kristin.kinney@AIFCmn.org', (SELECT id FROM companies WHERE name = 'American Indian Family Center' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Joe', 'Hobot', 'KatieF@AIOIC.org', (SELECT id FROM companies WHERE name = 'American Indian OIC' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Christina', 'Zeise', 'christina@ampersandfamilies.org', (SELECT id FROM companies WHERE name = 'Ampersand Families' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Holly', 'Leppanen', 'holly@annexteenclinic.org', (SELECT id FROM companies WHERE name = 'Annex Teen Clinic' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Alexis', 'Marchalek', 'Alexis@Aqwalife.org', (SELECT id FROM companies WHERE name = 'Aqwalife' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Leigh', 'Adams', 'LAdams@Ausherman.org', (SELECT id FROM companies WHERE name = 'Ausherman Family Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Katherine', 'Meerse', 'kmeerse@avenuesforyouth.org', (SELECT id FROM companies WHERE name = 'Avenues for Youth' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Melissa', 'Vine', 'director@thebeacondm.org', (SELECT id FROM companies WHERE name = 'The Beacon' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Genise', 'Aretz', 'ptollie@gmail.com', (SELECT id FROM companies WHERE name = 'Belle Plaine Food Shelf' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kellu', 'Tronstad', 'info@mybellis.org', (SELECT id FROM companies WHERE name = 'Bellis' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Molly', 'Koivumaki', 'molly@beyondnewbeginnings.org', (SELECT id FROM companies WHERE name = 'Beyond New Beginnings' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Josh', 'Reimnitz', 'jreimnitz@breakthroughtwincities.org', (SELECT id FROM companies WHERE name = 'Breakthrough Twin Cities' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Lisa', 'Mears', 'l.mears@bridgeforyouth.org', (SELECT id FROM companies WHERE name = 'Bridge for Youth' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jana', 'Shogren', 'info@bridgesofhopebrainerd.org', (SELECT id FROM companies WHERE name = 'Bridges of Hope' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Brittany', 'Wojtowicz', 'brittanyw@cadamn.org', (SELECT id FROM companies WHERE name = 'CADA' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Heather', 'Kilewer', 'heather.kliewer@caerfoodshelf.org', (SELECT id FROM companies WHERE name = 'CAER Food Shelf' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Bob', 'LaCroix', 'Bob@CampOmega.org', (SELECT id FROM companies WHERE name = 'Camp Omega' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Mary', 'Niedermeyer', 'mary.niedermeyer@capiusa.org', (SELECT id FROM companies WHERE name = 'CAPI' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Wendy', 'Petersen Bjorn', 'wbiorn@carvercountymn.gov', (SELECT id FROM companies WHERE name = 'Carver County Historical Society' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Clare', 'Brumback', 'clare.brumback@ceap.com', (SELECT id FROM companies WHERE name = 'Communnity Emergency Assistance Program (CEAP)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Curt', 'Gray', 'curtgray33@gmail.com', (SELECT id FROM companies WHERE name = 'Center for Coaching in Organizations' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jessica', 'Brandon', 'jbrandon@cmmhc.org', (SELECT id FROM companies WHERE name = 'Central Minnesota Mental Health Center' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Nora', 'Slawik', 'nora.slawik@century.edu', (SELECT id FROM companies WHERE name = 'Century College Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('David', 'Hamilton', 'DavidH@childcareawaremn.org', (SELECT id FROM companies WHERE name = 'Child Care Aware' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sarah', 'Driever', 'sarah.driever@childrensmn.org', (SELECT id FROM companies WHERE name = 'Children''s Hospital Association' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('BG', 'Tucker', 'hr@collegepossible.org', (SELECT id FROM companies WHERE name = 'College Possible' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Deidre', 'Schmidt', 'Deidre.Schmidt@commonbond.org', (SELECT id FROM companies WHERE name = 'CommonBond Communities' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Rita', 'Wiersma', 'executive.director@accordstpaul.org', (SELECT id FROM companies WHERE name = 'Accord' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Derrick', 'Jaeger', 'ExecutiveDirector@CommunityThread.org', (SELECT id FROM companies WHERE name = 'Community Thread' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Nalani', 'McCutcheon', 'Nalani.mccutcheon@conservationcorps.org', (SELECT id FROM companies WHERE name = 'Conservation Corps Minnesota and Iowa' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Christy', 'Shannon', 'Christy@CornerHouseMN.org', (SELECT id FROM companies WHERE name = 'Corner House' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Barbara', 'Hegge', 'customizedoptions@hotmail.com', (SELECT id FROM companies WHERE name = 'Customized Options' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Colleena', 'Carlisle', 'Colleena@dakotawoodlands.org', (SELECT id FROM companies WHERE name = 'Dakota Woodlands' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Mike', 'Lavin', 'mike.lavin@Darts1.org', (SELECT id FROM companies WHERE name = 'DARTS' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sheryl', 'Hill', 'sheryl@departsmart.com', (SELECT id FROM companies WHERE name = 'DepartSmart' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Maria', 'Kustritz', 'info@dunordfoundation.org', (SELECT id FROM companies WHERE name = 'DuNord Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Mike', 'Wynne', 'wynnem@emerge-mn.org', (SELECT id FROM companies WHERE name = 'Emerge' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jenna', 'Carter', 'jenna.carter@efmn.org', (SELECT id FROM companies WHERE name = 'Epilepsy Foundation of Minnesota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Susannah', 'Barnes', 'sbarnes@evolveservices.org', (SELECT id FROM companies WHERE name = 'EVOLVE Family Services' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Hanna', 'Getachew-Kreusser', 'getachew-kreusserh@face2face.org', (SELECT id FROM companies WHERE name = 'Face 2 Face' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Margaret', 'Korolchuk', 'Info@fcdc.org', (SELECT id FROM companies WHERE name = 'Family Child Development Center' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jody', 'Josten', 'jody@feediowa1st.com', (SELECT id FROM companies WHERE name = 'Feed Iowa First' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kate', 'King', 'kate.king@felinerescue.org', (SELECT id FROM companies WHERE name = 'Feline Rescue, Inc.' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Elaine', 'Grittner', 'kate.king@felinerescue.org', (SELECT id FROM companies WHERE name = 'Feline Rescue, Inc.' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kate', 'Burgraff', 'kateburggraff@ffen.org', (SELECT id FROM companies WHERE name = 'Foundations for Essential Needs' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jill', 'Hughes', 'director@finfood.org', (SELECT id FROM companies WHERE name = 'Friends in Need Food Shelf' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Rita', 'Thofern', 'rthofern@willowkinnifriends.org', (SELECT id FROM companies WHERE name = 'Friends of Willow River and Kinnickinnic State Parks' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Rachel', 'Lehman', 'rachel.lehman@greatexpectationsschool.org', (SELECT id FROM companies WHERE name = 'Great Expectations School' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Aaliyah', 'Hannah', 'Aaliyah@GreenCardVoices.org', (SELECT id FROM companies WHERE name = 'Green Card Voices' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Doug', 'Niemala', 'Doug@H2OforLifeSchools.org', (SELECT id FROM companies WHERE name = 'H2O For Life' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Phia', 'Xiong', 'phia.xiong@handyhelpllc.com', (SELECT id FROM companies WHERE name = 'Handy Help LLC' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jenna', 'Lebert', 'jenna@havenhouse.org', (SELECT id FROM companies WHERE name = 'Haven House' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Diana', 'Hawkins', 'dhawkins@hncmpls.org', (SELECT id FROM companies WHERE name = 'Hawthorne Neighborhood Council' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Rob', 'Thomas', 'Kmueller@HistoryTheatre.com', (SELECT id FROM companies WHERE name = 'History Theatre' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Karen', 'Mueller', 'Kmueller@HistoryTheatre.com', (SELECT id FROM companies WHERE name = 'History Theatre' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Txong', 'Pao Lee', 'txong@hmongcc.org', (SELECT id FROM companies WHERE name = 'Hmong Cultural Center' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('LaChelle', 'Williams', 'lwilliams@hope4youthmn.org', (SELECT id FROM companies WHERE name = 'HOPE 4 Youth' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sara', 'Kern', 'info@hope-coalition.org', (SELECT id FROM companies WHERE name = 'HOPE Coalition' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Dan', 'Pfarr', 'dan.pfarr@180degreed.org', (SELECT id FROM companies WHERE name = 'Hope House' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Dan', 'Narr', 'Dan@ICAFoodShelf.org', (SELECT id FROM companies WHERE name = 'ICA Food Shelf' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kevin', 'Ward', 'executivedirector@iocp.org', (SELECT id FROM companies WHERE name = 'Interfaith Outreach & Community Partners' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sarah', 'Vansickle', 'info@irishfair.com', (SELECT id FROM companies WHERE name = 'Irish Fair of Minnesota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Judy', 'Halper', 'jhalper@jfcsmpls.org', (SELECT id FROM companies WHERE name = 'Jewish Family and Children''s Services' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Marvin', 'Liszt', 'info@j-hap.org', (SELECT id FROM companies WHERE name = 'Jewish Programming and Housing (J-HAP)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Leah', 'Patton', 'leah@jrlc.org', (SELECT id FROM companies WHERE name = 'Joint Religious Legislative Coalition' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Darby', 'Lunceford', 'office@lakeshoreplayers.org', (SELECT id FROM companies WHERE name = 'Lakeshore Payers' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Martha', 'Moriarity', 'mm@ldaminnesota.org', (SELECT id FROM companies WHERE name = 'LDA Minnesota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jen', 'Lee', 'jlee@legalassist.org', (SELECT id FROM companies WHERE name = 'Legal Services of North Dakota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jordan', 'Lee Thompson', 'contact@listenupyouthradio.org', (SELECT id FROM companies WHERE name = 'Listen Up Youth Radio' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Anton', 'Jones', 'RaviKrishnan93@gmail.com', (SELECT id FROM companies WHERE name = 'Literacy Minnesota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Susan', 'Goodin', 'RaviKrishnan93@gmail.com', (SELECT id FROM companies WHERE name = 'Literacy Minnesota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('James', 'Falvey', 'jfalvey@friendsco.org', (SELECT id FROM companies WHERE name = 'Friends & Co' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Daniel', 'Gumnit', 'dgumnit@littlefreelibrary.org', (SELECT id FROM companies WHERE name = 'Little Free Library' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Al', 'Norby', 'anorby@loveinccc.org', (SELECT id FROM companies WHERE name = 'Love Inc.' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Stacy', 'Lung', 'licdirector@islandcamp.org', (SELECT id FROM companies WHERE name = 'Lutheran Island Camp' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Steve', 'Houtz', 'steven.houtz@macc-mn.org', (SELECT id FROM companies WHERE name = 'Metropolitan Alliance of Connected Communities (MACC)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Nancy', 'Gregory', 'ngregory@youthwayministries.org', (SELECT id FROM companies WHERE name = 'Manna Market' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jesse', 'Bethke-Gomez', 'jessebg@mcil-mn.org', (SELECT id FROM companies WHERE name = 'Metropolitan Center for Independent Living (MCIL)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Carrie', 'Opheim', 'carrie@mcleodfs.org', (SELECT id FROM companies WHERE name = 'McLeod Emergency Food Shelf' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sherry', 'Wichitchu', 'sherry@melsa.org', (SELECT id FROM companies WHERE name = 'MELSA' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Dan', 'Rodriguez', 'drodriguez@merrickcs.org', (SELECT id FROM companies WHERE name = 'Merrick Community Services' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sara', 'Patrick', 'Sara.Patrick@mro.net', (SELECT id FROM companies WHERE name = 'Midwest Reliability Organization' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Julie', 'Johnson', 'jjohnson@mssmn.org', (SELECT id FROM companies WHERE name = 'Midwest Special Services' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jeremy', 'Schreifels', 'jshreifels@milestone.org', (SELECT id FROM companies WHERE name = 'Milestone' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Ashley', 'Nathe', 'MplsFarmersMarket@gmail.com', (SELECT id FROM companies WHERE name = 'Minneapolis Farmers Market' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Ann', 'Mavity', 'anne.mavity@mhponline.org', (SELECT id FROM companies WHERE name = 'Minnesota Housing Partnership (MHP)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jennifer', 'Fink', 'Jennifer.Fink@newbrightonmn.gov', (SELECT id FROM companies WHERE name = 'Minnesota Parks and Recreation Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Ron', 'Busby Sr.', 'info@minnesotablackchamber.org', (SELECT id FROM companies WHERE name = 'MN Black Chamber of Commerce' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Romi', 'Slowiak', 'RomiSlowiak@gmail.com', (SELECT id FROM companies WHERE name = 'MN China Friendship Garden Society' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Bill', 'Zajicek', 'RomiSlowiak@gmail.com', (SELECT id FROM companies WHERE name = 'MN China Friendship Garden Society' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Matt', 'Dickhausen', 'mdickhausen@mn-mcea.org', (SELECT id FROM companies WHERE name = 'MN Community Education Association' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Anne', 'Gainey', 'ATGainey@gmail.com', (SELECT id FROM companies WHERE name = 'MN Community Health Workers Alliance' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kathy', 'Messerli', 'kmesserli@mnhomecare.org', (SELECT id FROM companies WHERE name = 'MN HomeCare Association' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Allen', 'Stauffer', 'al@tcgateway.com', (SELECT id FROM companies WHERE name = 'MN Metro North Tourism' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Travis', 'Smith', 'info@msboa.org', (SELECT id FROM companies WHERE name = 'MN School Bus Operators Association' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sandy', 'Schueller', 'sandy@msfca.org', (SELECT id FROM companies WHERE name = 'MN State Fire Chiefs Association' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Noah', 'Swiler', 'amy@mski.org', (SELECT id FROM companies WHERE name = 'MN Youth Ski League' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Amy', 'Cichanowski', 'amy@mski.org', (SELECT id FROM companies WHERE name = 'MN Youth Ski League' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jason', 'Swanson', 'Jswanson@MNRAAA.org', (SELECT id FROM companies WHERE name = 'MNRAAA' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Angela', 'Gauthier', 'email@movefwd.org', (SELECT id FROM companies WHERE name = 'MoveFwd Minnesota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jen', 'Wothe', 'info@msamn.com', (SELECT id FROM companies WHERE name = 'MN Subcontractors Association' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Deidre', 'Lynch Nicholson', 'dnichol-son@naehcy.org', (SELECT id FROM companies WHERE name = 'NAEHCY' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Karen', 'Goodenough', 'kgoodenough@socialworkers.org', (SELECT id FROM companies WHERE name = 'National Association of Social Workers' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Dawn', 'Wambeke', 'dawn@neighborsmn.org', (SELECT id FROM companies WHERE name = 'Neighbors, Inc.' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kathi', 'Kirchoff', 'nspfs@gmail.com', (SELECT id FROM companies WHERE name = 'North St. Paul Area Food Shelf' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jennifer', 'Freeburg', 'jennifer.freeburg@NCSIdaysupports.org', (SELECT id FROM companies WHERE name = 'Northeast Contemporary Services, Inc.' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jess', 'Nelson', 'jnelson@oasisforyouth.oth', (SELECT id FROM companies WHERE name = 'Oasis for Youth' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Tricia', 'Wright', 'tricia@onwardep.org', (SELECT id FROM companies WHERE name = 'Onward Eden Prairie' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jessica', 'Francis', 'jessica@opencupboard.org', (SELECT id FROM companies WHERE name = 'Open Cupboard' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Cindy', 'Ley', 'cindyl.opendoors@gmail.com', (SELECT id FROM companies WHERE name = 'Open Doors for Youth' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Shelly', 'Smith', 'shelly.smith@ourneighborsplace.org', (SELECT id FROM companies WHERE name = 'Our Neighbor''s Place' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Mike', 'Miner', 'mminer@paimn.org', (SELECT id FROM companies WHERE name = 'Phoenix Alternative, Inc.(PAI)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Julie', 'Zbaracki', 'julie@partnershipresources.org', (SELECT id FROM companies WHERE name = 'Partnership Resources, Inc.' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Peter', 'Schuna', 'consult@pathwayhealth.com', (SELECT id FROM companies WHERE name = 'Pathway Health Services' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Debby', 'Schuna', 'consult@pathwayhealth.com', (SELECT id FROM companies WHERE name = 'Pathway Health Services' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Darlene', 'Scott', 'dscott@phoenixresidence.org', (SELECT id FROM companies WHERE name = 'Phoenix Residence' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Veronica', 'Crosier', 'veronicac@PSAI.org', (SELECT id FROM companies WHERE name = 'Portable Sanitation Association International' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Pete', 'Steinke', 'paul@preservationalliance.com', (SELECT id FROM companies WHERE name = 'Preservation Alliance' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Michelle', 'Ness', 'mness@prismmpls.org', (SELECT id FROM companies WHERE name = 'PRISM' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Katie', 'Holmgren', 'kholgren@projectpathfinder.org', (SELECT id FROM companies WHERE name = 'Project Pathfinder' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Mohannad', 'Ghawanmeh', 'mohannad@publicartsstpaul.org', (SELECT id FROM companies WHERE name = 'Public Arts St. Paul' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Michelle', 'Belitz', 'michelle.belitz@CO.RAMSEY.MN.US', (SELECT id FROM companies WHERE name = 'Ramsey County Workforce Solutions' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Joan', 'Twiton', 'jtwiton@relatemn.org', (SELECT id FROM companies WHERE name = 'Relate Counseling Center' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Tracie', 'Stanton', 'tracie@resourcewest.org', (SELECT id FROM companies WHERE name = 'Resource West' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Craig', 'Moriak', 'Moriak.Ent@gmail.com', (SELECT id FROM companies WHERE name = 'Ridgeview Senior Apartments' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Marc', 'Morrison', 'info@rreal.org', (SELECT id FROM companies WHERE name = 'Rural Renewable Energy Alliance (RREAL)' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Tabitha', 'Montgomery', 'tabitha@seward.coop', (SELECT id FROM companies WHERE name = 'Seward Community Co-Op' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Cherie', 'Matson', 'sibleycountyfoodshare@gmail.com', (SELECT id FROM companies WHERE name = 'Sibley County FoodShare' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Diamond', 'Hunter', 'Dhunter@solidgroundmn.org', (SELECT id FROM companies WHERE name = 'Solid Ground' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sara', 'Meeks', 'Dhunter@solidgroundmn.org', (SELECT id FROM companies WHERE name = 'Solid Ground' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Laurie', 'Brownelkl', 'laurie@semaaa.org', (SELECT id FROM companies WHERE name = 'Southeast Minnesota Area Agency on Aging' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Josh', 'Munsch', 'josh@southsideservices.org', (SELECT id FROM companies WHERE name = 'Southside Services I. INC.' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Kara', 'Schommer', 'kara.schommer@gmail.com', (SELECT id FROM companies WHERE name = 'St. Paul Community Literacy Consortium' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Mary', 'Larew', 'mary@thespcm.org', (SELECT id FROM companies WHERE name = 'St. Paul Conservatory of Music' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Nina', 'Archabal', 'mary@thespcm.org', (SELECT id FROM companies WHERE name = 'St. Paul Conservatory of Music' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Deborah', 'Moses', 'Kyle.Hanson@agatemn.org', (SELECT id FROM companies WHERE name = 'Agate Housing and Services' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Carrie', 'Zelin Johnson', 'carrie@startearlyfunders.org', (SELECT id FROM companies WHERE name = 'Start Early Funders Coalition' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Tracy', 'Keibler', 'tracy@startseniorsolutions.org', (SELECT id FROM companies WHERE name = 'START Senior Solutions' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Alicia', 'Hause', 'ahouse@rummlerHOPE.org', (SELECT id FROM companies WHERE name = 'Steve Rummler Hope Network' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Elsbeth', 'Howe', 'splf@stillwaterlibraryfoundation.org', (SELECT id FROM companies WHERE name = 'Stillwater Public Library Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Okpara', 'Rice', 'orice@tanagerplace.org', (SELECT id FROM companies WHERE name = 'Tanager Place' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Dawn', 'Simonsen', 'dsimonsen@trellisconnects.org', (SELECT id FROM companies WHERE name = 'Trellis' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Trevor', 'Johnson', 'info@tasksunlimited.org', (SELECT id FROM companies WHERE name = 'Tasks Unlimited' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Ross', 'Dunbar', 'isthmusfoundation.org', (SELECT id FROM companies WHERE name = 'The Isthmus Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('James', 'Dutton', 'isthmusfoundation.org', (SELECT id FROM companies WHERE name = 'The Isthmus Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Cathy', 'Heying', 'cathy@theliftgarage.org', (SELECT id FROM companies WHERE name = 'The Lift Garage' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Beth', 'Holger', 'bholger@thelinkmn.org', (SELECT id FROM companies WHERE name = 'The Link' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Rick', 'Robbins', 'robbinsr@partnershipplan.org', (SELECT id FROM companies WHERE name = 'The Partnership Plan' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Brandon', 'Ferdig', 'brandon@theperiphery.com', (SELECT id FROM companies WHERE name = 'The Periphery Foundation' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Cisa', 'Keller', 'info@thinksmall.org', (SELECT id FROM companies WHERE name = 'Think Small' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('MJ', 'Carpio', 'mjc@movemn.org', (SELECT id FROM companies WHERE name = 'Move Minnesota' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Christina', 'Miller', 'christina@mathrecovery.org', (SELECT id FROM companies WHERE name = 'US Math Recovery Council' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Jonna', 'Phillips', 'jonna@veteranresilience.org', (SELECT id FROM companies WHERE name = 'Veteran Resilience Project' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Sara', 'Hanson', 'office@whitebearhistory.org', (SELECT id FROM companies WHERE name = 'White Bear Lake Area Historical Society' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Rich', 'Melzer', 'rmelzer@youthlinkmn.org', (SELECT id FROM companies WHERE name = 'YouthLink' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW()),
('Perry', 'Peterson', 'perry@whitebearfoodshelf.org', (SELECT id FROM companies WHERE name = 'White Bear Area Food Shelf' AND organization_id = 7 LIMIT 1), 7, NOW(), NOW());

-- Verify contacts were inserted
SELECT COUNT(*) as contact_count 
FROM contacts 
WHERE organization_id = 7;

-- Show sample of inserted contacts with their companies
SELECT 
    c.first_name,
    c.last_name,
    c.email,
    comp.name as company_name
FROM contacts c
LEFT JOIN companies comp ON c.company_id = comp.id
WHERE c.organization_id = 7
ORDER BY c.created_at DESC
LIMIT 10;