[build]
  # Let Netlify auto-detect Next.js and handle the build
  base = "."

[build.environment]
  # Node.js version - using LTS version that's compatible with npm
  NODE_VERSION = "20"
  
  # Ensure npm version compatibility
  NPM_VERSION = "10"
  
  # Use npm instead of pnpm
  NPM_FLAGS = "--production=false"
  
  # API base URL for production - Railway backend
  NEXT_PUBLIC_API_URL = "https://nohubspot-production.up.railway.app"