[build]
  # Use standard Next.js build with Netlify auto-detection
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Base directory for the build (root of the project)
  base = "."

[build.environment]
  # Node.js version - using LTS version that's compatible with npm
  NODE_VERSION = "20"
  
  # Ensure npm version compatibility
  NPM_VERSION = "10"
  
  # Use npm instead of pnpm
  NPM_FLAGS = "--production=false"
  
  # API base URL for production - Railway backend
  NEXT_PUBLIC_API_URL = "https://nohubspot-production.up.railway.app"