[build]
  # Use Next.js with static export for Netlify
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Directory where the built files are located
  publish = "out"
  
  # Base directory for the build (root of the project)
  base = "."

[build.environment]
  # Node.js version - using LTS version that's compatible with npm
  NODE_VERSION = "20"
  
  # Ensure npm version compatibility
  NPM_VERSION = "10"
  
  # Use npm instead of pnpm
  NPM_FLAGS = "--production=false"
  
  # API base URL for production - Railway backend
  NEXT_PUBLIC_API_URL = "https://nohubspot-production.up.railway.app"

# Handle subdomain routing - all subdomains should serve the same app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Domain = ["*.nothubspot.app"]}

# Handle main domain routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Domain aliases - tell Netlify to accept all subdomains
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true