[build]
  # Explicit Next.js build command and publish directory
  command = "npm run build && cp _redirects .next/_redirects"
  publish = ".next"

[build.environment]
  # Node.js version - using LTS version that's compatible with npm
  NODE_VERSION = "20"
  
  # Ensure npm version compatibility
  NPM_VERSION = "10"
  
  # Use npm instead of pnpm
  NPM_FLAGS = "--production=false"
  
  # API base URL for production - Railway backend
  NEXT_PUBLIC_API_URL = "https://nohubspot-production.up.railway.app"

# Force Netlify to treat this as a Next.js SSR app with serverless functions
[[plugins]]
  package = "@netlify/plugin-nextjs"