[build]
  # Use Next.js plugin for proper Netlify integration
  command = "npm install --legacy-peer-deps && npm run build && npm run export"
  
  # Directory where the built files are located
  publish = "out"
  
  # Base directory for the build (root of the project)
  base = "."

[build.environment]
  # Node.js version - using LTS version that's compatible with npm
  NODE_VERSION = "20"
  
  # Ensure npm version compatibility
  NPM_VERSION = "10"
  
  # Use npm instead of pnpm
  NPM_FLAGS = "--production=false"
  
  # API base URL for production (you'll need to update this to your backend URL)
  NEXT_PUBLIC_API_URL = "https://your-backend-url.com"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200