[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--production=false"
  NEXT_PUBLIC_API_URL = "https://nohubspot-production.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Correct syntax for subdomain redirects
[[redirects]]
  from = "/*"
  to = "https://nothubspot.app/:splat"
  status = 200
  force = true
  conditions = {Host = ["*.nothubspot.app"]}