-- NotHubSpot Data Upload SQL Script
-- Generated: 2025-07-14 16:41:21
-- Companies: 167
-- Contacts: 182

-- ============================================
-- IMPORTANT: READ BEFORE RUNNING
-- ============================================
-- 1. First run the SELECT queries to get your organization and user IDs
-- 2. Replace {ORG_ID} and {USER_ID} with the actual values
-- 3. Run the INSERT statements in order (companies first, then contacts)
-- ============================================

-- Step 1: Find your organization ID
SELECT id, name, slug 
FROM organizations 
WHERE slug = 'strategic-consulting-coaching-llc-vo2w';

-- Step 2: Find your user ID  
SELECT id, email, first_name, last_name 
FROM users 
WHERE email = 'eleblow@bmhmn.com';

-- ============================================
-- REPLACE {ORG_ID} and {USER_ID} below with actual values from above queries!
-- ============================================


-- Insert Companies (run this first)
INSERT INTO companies (
    name, street_address, city, state, postal_code, website, description, status,
    organization_id, created_by_id, created_at, updated_at
) VALUES
('Advocating Change Together (ACT)', '1821 University Ave W S177', 'St. Paul', 'MN', '55104', NULL, 'Jen Walton is the new Executive Director', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('American Indian Family Center', '579 Wells St', 'St. Paul', 'MN', '55130', NULL, '6/5/25 Submitting Proposal for Search', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('American Association of Woodturners', 'Landmark Center', 'St. Paul', 'MN', '55102', NULL, 'ED just left', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('American Indian OIC', '1845 E Franklin Ave', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ampersand Families', '1751 County Rd B West, Ste 300', 'Roseville', 'MN', '55113', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Annex Teen Clinic', '5810 N 42nd Ave', 'Robbinsdale', 'MN', '55422', NULL, 'old', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Aqwalife', '1 Four Coins Drive', 'Canonsburg', 'PA', '15317', NULL, 'old', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Arcola Mills', 'PO Box 313', 'Stillwater', 'MN', '55082', NULL, 'Google has noted it is temporarily closed. Cecily: Actually they tried to recruit me for the Board. They are coming back after issues with May Township', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ausherman Family Foundation', '7420 Hayward Rd #203', 'Frederick', 'MD', '21702', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Avenues for Youth', '1708 Oakland Park Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('The Beacon', '1717 Woodland Ave', 'Des Moines', 'MN', '50309', NULL, 'Note - I just did a Google Search and found an article in the Des Moines Busines Journal from September 2024 announcing the search for a new ED. I''ll reach out to see if I can find out who the new contact is.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Belle Plaine Food Shelf', '128 N Meridian St', 'Belle Plaine', 'MN', '56011', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Bellis', '2038 Ford Pkwy, PMB 457', 'St Paul', 'MN', '55116', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Beyond New Beginnings', '5666 Lincoln Dr Ste 210', 'Edina', 'MN', '55436', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Big Lake Community Food Shelf', '160 Lake St N', 'Big Lake', 'MN', '55309', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Breakthrough Twin Cities', '2051 Larpenteur Ave E', 'St. Paul', 'MN', '55109', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Bridge for Youth', '1111 W 22nd St', 'Minneapolis', 'MN', '55405', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Bridges of Hope', '2011 S 6th St', 'Brainerd', 'MN', '56401', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('CADA', NULL, NULL, NULL, NULL, NULL, 'I see on linked in that their previous ED whom I worked with is no longer with the org.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('CAER Food Shelf', '12621 Elk Lake Rd NW', 'Elk River', 'MN', '55330', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Camp Omega', '22750 Lind Ave', 'Waterville', 'MN', '56096', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('CAPI', '5930 Brooklyn Blvd', 'Minneapolis', 'MN', '55429', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Carver County Historical Society', '555 W 1st St', 'Waconia', 'MN', '55387', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Communnity Emergency Assistance Program (CEAP)', '7051 Brooklyn Blvd', 'Brooklyn Center', 'MN', '55429', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Center for Coaching in Organizations', '8216 W 102nd St', 'Bloomington', 'MN', '55438', NULL, 'Proposal in 2024 - Declined', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Central Minnesota Mental Health Center', '411 3rd St N', 'Waite Park', 'MN', '56387', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Century College Foundation', 'East Campus, E2507', 'White Bear Lake', 'MN', '55110', NULL, 'NOTE: NORA REQUESTED TO NO LONGER RECEIVE EMAILS FROM US 7.1.2025
ED is retiring this spring . Cecily: I know Nora Slawik from SACF, Is this retiring?', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Child Care Aware', '10 River Park Plaza #820', 'St. Paul', 'MN', '55107', NULL, 'ED retired in May 2025.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Children''s Hospital Association', '347 Smith Ave N #501', 'St. Paul', 'MN', '55102', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('College Possible', '755 Prior Ave N Ste 200', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('CommonBond Communities', '1080 Montreal Ave', 'St. Paul', 'MN', '55116', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Accord', '1515 Energy Park Dr', 'St. Paul', 'MN', '55108', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Community Thread', '2300 Orleans St W', 'Stillwater', 'MN', '55082', NULL, 'Sally retired- new ED is Derrick Jaeger. Email retuned as undeliverable.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Conservation Corps Minnesota and Iowa', '60 Plato Blvd', 'St. Paul', 'MN', '55107', NULL, 'I know Haley Nelson, their recruitment manager. We were on the FFEN Bd together- Andrea', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Corner House', '2502 10th Ave S', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Customized Options', '7447 4th St N', 'Oakdale', 'MN', '55128', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Dakota Woodlands', '3430 Wescott Woodlands', 'Eagan', 'MN', '55123', NULL, 'Jennifer Harrison has left, but I see on Linked In that JoHana Smrcina who I worked with at the Lift Garage is now their Director of Housing. Ceily: Added ED', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('DARTS', '1645 Marthaler Ln', 'West St. Paul', 'MN', '55118', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('DepartSmart', '5775 Wayzata Blvd #700', 'St. Louis Park', 'MN', '55416', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Dispute Resolution Center', '844 Selby Ave', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('DuNord Foundation', '2610 E 32nd St', 'Minneapolis', 'MN', '55406', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Emerge', '1834 Emerson Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Epilepsy Foundation of Minnesota', '7760 France Ave S Ste 210', 'Bloomington', 'MN', '55435', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('EVOLVE Family Services', '5850 Omaha Ave N', 'Stillwater', 'MN', '55082', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Face 2 Face', '1165 Arcade St', 'St. Paul', 'MN', '55106', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Family Child Development Center', '100 Nathan Lane N', 'Minneapolis', 'MN', '55441', NULL, 'No email in contract. Her testimonial on SCC website', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Feed Iowa First', '1506 10th St SE', 'Cedar Rapids', 'IA', '52401', NULL, 'I think this was Emily. New ED in 2024', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Feline Rescue, Inc.', '593 Fairview Ave N', 'St. Paul', 'MN', '55104', NULL, 'Met with Kate King recently. FR is doing great under her leadership, staff has increased, new board members, Completed an internal strategic planning process.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Financial One Credit Union', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Foundations for Essential Needs', '701 N 3rd ST #203', 'Minneapolis', 'MN', '55401', NULL, 'I was on their board and am close friend with Kate Burgraff. My duaghter babysits for her boys - Andrea', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Friends in Need Food Shelf', '535 4th St', 'St. Paul Park', 'MN', '55071', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Friends of St. Paul College Foundation', '235 Marshall Ave', 'St. Paul', 'MN', '55102', 'https://www.saintpaul.edu/alumni/friends/#about', NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Friends of Willow River and Kinnickinnic State Parks', '1034 County Road A', 'Hudson', 'WI', '54016', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Great Expectations School', '550 5th St', 'Grand Marais', 'MN', '55604', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Green Card Voices', '2611 1st Ave S', 'Minneapolis', 'MN', '55408', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('H2O For Life', '4756 Banning Ave #207', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Handy Help LLC', '2365 McKnight Rd N', 'Maplewood', 'MN', '55109', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Haven House', '1803 Bryant Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Hawkinson Fund for Peace and Justice', '324 Harvard St SE', 'Minneapolis', 'MN', '55414', 'https://www.unitedseminary.edu/lcsj/hawkinsonfund/', 'The Hawkinson Fund for Peace and Justice has moved to the Leadership Center for Social Justice at United Theological Seminary of the Twin Cities', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Hawthorne Neighborhood Council', '2944 Emerson Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('History Theatre', '30 10th St E', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Hmong Cultural Center', '375 University Ave W #204', 'St. Paul', 'MN', '55103', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('HOPE 4 Youth', '10250 Foley Blvd NW #48010', 'Coon Rapids', 'MN', '55448', NULL, 'I used to work there as the VP of Advancement. Still close with NIkki Shapiro their Dir of Advancement- Andrea', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('HOPE Coalition', '1926 Old W Main St Ste 104', 'Red Wing', 'MN', '55066', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Hope House', '3010 W 78th St', 'Excelsior', 'MN', '55331', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('ICA Food Shelf', '11588 K-Tel Dr', 'Minnetonka', 'MN', '55343', NULL, 'Ex Dir is Dan Narr- I worked with him many moons ago at Catholic Charities - Andrea', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Interfaith Outreach & Community Partners', '1605 County Rd 101', 'Plymouth', 'MN', '55447', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Irish Fair of Minnesota', '836 Prior Ave N Ste 500', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jewish Family and Children''s Services', '5905 Golden Valley Rd', 'Golden Valley', 'MN', '55422', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jewish Programming and Housing (J-HAP)', '9280 Golden Valley Rd #140', 'Golden Valley', 'MN', '55427', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Joint Religious Legislative Coalition', '122 W Franklin Ave', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Joyce Uptown Food Shelf', '3041 Fremont Ave S', 'Minneapolis', 'MN', '55408', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Lakeshore Payers', '4941 Long Ave', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('LDA Minnesota', '5101 Olson Memorial Hwy Ste 6000', 'Minneapolis', 'MN', '55422', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Legal Services of North Dakota', '418 E Broadway Ste 25', 'Bismarck', 'ND', '58501', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Listen Up Youth Radio', '550 Vandalia St Ste 170', 'St. Paul', 'MN', '55114', NULL, 'Emily Krumberger was our contact at the time of Emily Z''s departure', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Literacy Minnesota', '700 Raymond Ave #180', 'St. Paul', 'MN', '55114', NULL, 'Ravi is past board chair', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Friends & Co', '2550 University Ave W Ste 260-S', 'St. Paul', 'MN', '55114', NULL, 'Formerly Little Brothers Friends of the Elderly', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Little Earth', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Little Free Library', '2327 Wycliff St Ste 220', 'St. Paul', 'MN', '55114', NULL, 'Greig Meitzer retiring this summer, ED is now Daniel Gumnit', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Love Inc.', '1600 Bavaria Rd', 'Chaska', 'MN', '55318', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Lutheran Island Camp', '45011 230th St', 'Henning', 'MN', '56551', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Metropolitan Alliance of Connected Communities (MACC)', '3433 Broadway St NE Ste 230', 'Minneapolis', 'MN', '55413', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Manna Market', '3301 92nd Ave NE', 'Blaine', 'MN', '55449', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Metropolitan Center for Independent Living (MCIL)', '530 Robert St N', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('McLeod Emergency Food Shelf', '719 13th St E', 'Glencoe', 'MN', '55336', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MDE', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Meeker County Emergency Food Shelf', '118 N Sibley Ave', 'Litchfield', 'MN', '55355', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MELSA', '1619 W Dayton Ave #314', 'St. Paul', 'MN', '55104', NULL, 'New ED with solid skills. Changes with State budget have not yet impacted MELSA. However, concerns about libraries across Minnesota.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Merrick Community Services', '1669 Arcade St Ste 4', 'St. Paul', 'MN', '55106', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Midwest Reliability Organization', '380 St Peter St #800', 'St. Paul', 'MN', '55102', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Midwest Special Services', '900 Ocean St', 'St. Paul', 'MN', '55106', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Milestone', '1821 University Ave W S 164', 'St. Paul', 'MN', '55104', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Minneapolis Farmers Market', '312 E Lyndale Ave N', 'Minneapolis', 'MN', '55405', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Minnesota Housing Partnership (MHP)', '2446 University Ave W #106', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Minnesota Parks and Recreation Foundation', '200 Charles St NE', 'Fridley', 'MN', '55432', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN Black Chamber of Commerce', '401 Robert St N #150', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN China Friendship Garden Society', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN Community Education Association', '13750 Lake Blvd', 'Lindstrom', 'MN', '55045', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN Community Health Workers Alliance', '2250 University Ave W Ste 200N', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN HomeCare Association', '1265 Grey Fox Rd Ste 2', 'Arden Hills', 'MN', '55112', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN Metro North Tourism', '7071 University Ave NE', 'Fridley', 'MN', '55432', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN School Bus Operators Association', '1611 County B Rd W', 'St. Paul', 'MN', '55113', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN State Community and Technical College Foundation', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN State Fire Chiefs Association', '1433 Idaho Ave W', 'St. Paul', 'MN', '55108', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN Youth Ski League', 'PO Box 18659', 'Minneapolis', 'MN', '55418', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MNRAAA', '201 North Broad St Ste 102', 'Mankato', 'MN', '56001', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Minnesota Organization for Habilitation and Rehabilitation(MOHR)', '2027 Rice St', 'Roseville', 'MN', '55113', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MoveFwd Minnesota', '1001 MN-7 #237', 'Hopkins', 'MN', '55305', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MN Subcontractors Association', '4248 Park Glen Rd', 'Minneapolis', 'MN', '55416', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('NAEHCY', '13570 Grove Drive #302', 'Maple Grove', 'MN', '55311', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('National Association of Social Workers', 'PO Box 92', 'Backus', 'MN', '56435', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Neighbors, Inc.', '222 Grand Ave W', 'South St. Paul', 'MN', '55075', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('North St. Paul Area Food Shelf', '2266 2nd St N', 'St. Paul', 'MN', '55109', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Northeast Contemporary Services, Inc.', '2782 Cleveland Ave N', 'Roseville', 'MN', '55113', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Oasis for Youth', '2200 W Old Shakopee Rd', 'Bloomington', 'MN', '55431', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Onward Eden Prairie', 'PO Box 44863', 'Eden Prairie', 'MN', '55344', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Open Cupboard', '8264 4th St N', 'Oakdale', 'MN', '55128', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Open Doors for Youth', '554 3rd St NW Ste 201', 'Elk River', 'MN', '55330', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Our Neighbor''s Place', '122 W Johnson St', 'River Falls', 'WI', '54022', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Phoenix Alternative, Inc.(PAI)', '3700 Highway 61 N Ste 200', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Partnership Resources, Inc.', '1069 10th Ave SE', 'Minneapolis', 'MN', '55414', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Pathway Health Services', '11240 Stillwater Blvd', 'Lake Elmo', 'MN', '55042', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Phoenix Residence', '222 Plato Blvd', 'St. Paul', 'MN', '55107', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Portable Sanitation Association International', '1601 Utica Ave S Ste 213', 'Minneapolis', 'MN', '55416', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Preservation Alliance', 'Landmark Center', 'St. Paul', 'MN', '55102', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('PRISM', '1220 Zane Ave N', 'Golden Valley', 'MN', '55422', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Project Pathfinder', '570 N Asbury St #300', 'St. Paul', 'MN', '55104', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Public Arts St. Paul', '370 Wabasha St N Ste 114', 'St. Paul', 'MN', '55102', NULL, 'Email returned as undeliverable
The people that i worked with are gone now, but we could reach out.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ramsey County Workforce Solutions', '121 7th Pl E #2100', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ampact', '2400 Park Ave', 'Minneapolis', 'MN', '55404', NULL, 'Formerly Reading & Math, Inc', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Relate Counseling Center', '5125 County Rd 101', 'Minnetonka', 'MN', '55345', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('RESOURCE', '1900 Chicago Ave S', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Resource West', '1011 1st St S', 'Hopkins', 'MN', '55343', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ridgeview Senior Apartments', '390 5th St NW #108', 'Clear Lake', 'MN', '54005', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Rural Renewable Energy Alliance (RREAL)', '3963 8th St SW', 'Backus', 'MN', '56435', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Seward Community Co-Op', '2823 E Franklin Ave', 'Minneapolis', 'MN', '55406', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sibley County FoodShare', '111 Industrial Ave S', 'Gaylord', 'MN', '55334', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('SOAR Regional Arts', 'PO Box 372', 'St. Michael', 'MN', '55376', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Solid Ground', '3521 Century Ave N', 'White Bear Lake', 'MN', '55110', NULL, 'I worked here as Dir of Advancement - Andrea', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Som Gum Cooperative', '5010 Washington St NE', 'Minneapolis', 'MN', '55421', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Somerset Community Food Pantry', 'PO Box 297', 'Somerset', 'WI', '54025', NULL, 'This was Heidi, Cecily can try to reach out to them if desired', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Southeast Minnesota Area Agency on Aging', '2720 Superior Dr NW #102', 'Rochester', 'MN', '55901', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Southside Services I. INC.', '1845 E Lake St #200', 'Minneapolis', 'MN', '55407', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('St. Paul Community Literacy Consortium', '700 Raymond Ave #180', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('St. Paul Conservatory of Music', '1619 Dayton Ave Ste 200', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Agate Housing and Services', '2309 Nicollet Ave', 'Minneapolis', 'MN', '55404', NULL, 'Current ED is Kyle Hanson Kyle.Hanson@agatemn.org, was St Stephens', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Start Early Funders Coalition', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('START Senior Solutions', '6995 Mariann Dr', 'Eden Prairie', 'MN', '55346', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Steve Rummler Hope Network', '2233 University Ave W Ste 325', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Stillwater Public Library Foundation', '224 North Third St', 'Stillwater', 'MN', '55082', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Tanager Place', '1030 5th Ave SE', 'Cedar Rapids', 'IA', '52403', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Trellis', '1265 Grey Fox Rd Ste 2', 'Arden Hills', 'MN', '55112', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Tasks Unlimited', '2419 Nicollet Ave', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('The Annex Teen Clinic', '2748 Lyndale Ave S', 'Minneapolis', 'MN', '55408', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('The Isthmus Foundation', '10141 Irwin Rd', 'Minneapolis', 'MN', '55437', NULL, 'Recently spoke with Ross. He reported that they are currently doing well.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('The Lift Garage', '2401 E Lake St', 'Minneapolis', 'MN', '55406', NULL, 'JoHanna has left.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('The Link', '1210 Glenwood Ave', 'Minneapolis', 'MN', '55405', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('The Partnership Plan', '1875 Greeley St S', 'Stillwater', 'MN', '55082', NULL, 'Cecily: I know their current DD consultant', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('The Periphery Foundation', '5322 Maywood Rd Ste 3', 'Mound', 'MN', '55364', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Think Small', '10 Yorkton Ct', 'St. Paul', 'MN', '55117', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Move Minnesota', '2356 University Ave W', 'St. Paul', 'MN', '55114', NULL, 'Was once Transit for Livable Communities', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('US Math Recovery Council', '510 Lone Oak Rd', 'Eagan', 'MN', '55121', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Veteran Resilience Project', 'PO Box 1057', 'Minnetonka', 'MN', '55345', NULL, 'VRP lost their funding through the state legislature this session between $200 to $400,000 so significant decrease. This will possibly mean layoffs. Currently working with Access Philanthropy.', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('White Bear Lake Area Historical Society', '2228 4th St', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('YouthLink', '41 N 12th St', 'Minneapolis', 'MN', '55403', NULL, 'Email returned as undeliverable', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW()),
('White Bear Area Food Shelf', '1884 Whitaker St', 'White Bear Lake', 'MN', '55110', NULL, 'Renae was the interim director that hired me as their Ex Dir many moons ago. I know they need help. - Andrea', 'Active', {ORG_ID}, {USER_ID}, NOW(), NOW());

-- Verify companies were inserted and get their IDs
SELECT id, name 
FROM companies 
WHERE organization_id = {ORG_ID}
ORDER BY created_at DESC
LIMIT 167;


-- Insert Contacts (run this after companies)
-- This uses a subquery to find the company ID by name
INSERT INTO contacts (
    first_name, last_name, email, company_id,
    organization_id, created_by_id, created_at, updated_at
) VALUES
('Jen', 'Walton', 'act@selfadvocacy.org', (SELECT id FROM companies WHERE name = 'Advocating Change Together (ACT)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kristin', 'Kinney', 'kristin.kinney@AIFCmn.org', (SELECT id FROM companies WHERE name = 'American Indian Family Center' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Joe', 'Hobot', 'KatieF@AIOIC.org', (SELECT id FROM companies WHERE name = 'American Indian OIC' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Christina', 'Zeise', 'christina@ampersandfamilies.org', (SELECT id FROM companies WHERE name = 'Ampersand Families' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Holly', 'Leppanen', 'holly@annexteenclinic.org', (SELECT id FROM companies WHERE name = 'Annex Teen Clinic' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Alexis', 'Marchalek', 'Alexis@Aqwalife.org', (SELECT id FROM companies WHERE name = 'Aqwalife' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Leigh', 'Adams', 'LAdams@Ausherman.org', (SELECT id FROM companies WHERE name = 'Ausherman Family Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Katherine', 'Meerse', 'kmeerse@avenuesforyouth.org', (SELECT id FROM companies WHERE name = 'Avenues for Youth' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Melissa', 'Vine', 'director@thebeacondm.org', (SELECT id FROM companies WHERE name = 'The Beacon' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Genise', 'Aretz', 'ptollie@gmail.com', (SELECT id FROM companies WHERE name = 'Belle Plaine Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kellu', 'Tronstad', 'info@mybellis.org', (SELECT id FROM companies WHERE name = 'Bellis' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Molly', 'Koivumaki', NULL, (SELECT id FROM companies WHERE name = 'Beyond New Beginnings' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Josh', 'Reimnitz', 'jreimnitz@breakthroughtwincities.org', (SELECT id FROM companies WHERE name = 'Breakthrough Twin Cities' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Lisa', 'Mears', 'l.mears@bridgeforyouth.org', (SELECT id FROM companies WHERE name = 'Bridge for Youth' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jana', 'Shogren', 'info@bridgesofhopebrainerd.org', (SELECT id FROM companies WHERE name = 'Bridges of Hope' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Brittany', 'Wojtowicz', 'brittanyw@cadamn.org', (SELECT id FROM companies WHERE name = 'CADA' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Heather', 'Kilewer', 'heather.kliewer@caerfoodshelf.org', (SELECT id FROM companies WHERE name = 'CAER Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Bob', 'LaCroix', 'Bob@CampOmega.org', (SELECT id FROM companies WHERE name = 'Camp Omega' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Mary', 'Niedermeyer', 'mary.niedermeyer@capiusa.org', (SELECT id FROM companies WHERE name = 'CAPI' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Wendy', 'Petersen Bjorn', 'wbiorn@carvercountymn.gov', (SELECT id FROM companies WHERE name = 'Carver County Historical Society' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Clare', 'Brumback', 'clare.brumback@ceap.com', (SELECT id FROM companies WHERE name = 'Communnity Emergency Assistance Program (CEAP)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Curt', 'Gray', 'curtgray33@gmail.com', (SELECT id FROM companies WHERE name = 'Center for Coaching in Organizations' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jessica', 'Br', 'jbrandon@cmmhc.org', (SELECT id FROM companies WHERE name = 'Central Minnesota Mental Health Center' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('on', '', 'jbrandon@cmmhc.org', (SELECT id FROM companies WHERE name = 'Central Minnesota Mental Health Center' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Nora', 'Slawik', 'nora.slawik@century.edu', (SELECT id FROM companies WHERE name = 'Century College Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('David', 'Hamilton', 'DavidH@childcareawaremn.org', (SELECT id FROM companies WHERE name = 'Child Care Aware' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sarah', 'Driever', 'sarah.driever@childrensmn.org', (SELECT id FROM companies WHERE name = 'Children''s Hospital Association' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('BG', 'Tucker', 'hr@collegepossible.org', (SELECT id FROM companies WHERE name = 'College Possible' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Deidre', 'Schmidt', 'Deidre.Schmidt@commonbond.org', (SELECT id FROM companies WHERE name = 'CommonBond Communities' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Rita', 'Wiersma', 'executive.director@accordstpaul.org', (SELECT id FROM companies WHERE name = 'Accord' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Derrick', 'Jaeger', 'ExecutiveDirector@CommunityThread.org', (SELECT id FROM companies WHERE name = 'Community Thread' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Nalani', 'McCutcheon', 'Nalani.mccutcheon@conservationcorps.org', (SELECT id FROM companies WHERE name = 'Conservation Corps Minnesota and Iowa' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Christy', 'Shannon', 'Christy@CornerHouseMN.org', (SELECT id FROM companies WHERE name = 'Corner House' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Barbara', 'Hegge', 'customizedoptions@hotmail.com', (SELECT id FROM companies WHERE name = 'Customized Options' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Colleena', 'Carlisle', 'Colleena@dakotawoodlands.org', (SELECT id FROM companies WHERE name = 'Dakota Woodlands' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Mike', 'Lavin', 'mike.lavin@Darts1.org', (SELECT id FROM companies WHERE name = 'DARTS' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('President', '', 'mike.lavin@Darts1.org', (SELECT id FROM companies WHERE name = 'DARTS' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sheryl', 'Hill', NULL, (SELECT id FROM companies WHERE name = 'DepartSmart' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Maria', 'Kustritz', 'info@dunordfoundation.org', (SELECT id FROM companies WHERE name = 'DuNord Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Mike', 'Wynne', 'wynnem@emerge-mn.org', (SELECT id FROM companies WHERE name = 'Emerge' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jenna', 'Carter', 'jenna.carter@efmn.org', (SELECT id FROM companies WHERE name = 'Epilepsy Foundation of Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Susannah', 'Barnes', 'sbarnes@evolveservices.org', (SELECT id FROM companies WHERE name = 'EVOLVE Family Services' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Hanna', 'Getachew-Kreusser', 'getachew-kreusserh@face2face.org', (SELECT id FROM companies WHERE name = 'Face 2 Face' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Margaret', 'Korolchuk', 'Info@fcdc.org', (SELECT id FROM companies WHERE name = 'Family Child Development Center' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jody', 'Josten', 'jody@feediowa1st.com', (SELECT id FROM companies WHERE name = 'Feed Iowa First' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kate', 'King', 'kate.king@felinerescue.org', (SELECT id FROM companies WHERE name = 'Feline Rescue, Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'kate.king@felinerescue.org', (SELECT id FROM companies WHERE name = 'Feline Rescue, Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Elaine', 'Grittner', 'kate.king@felinerescue.org', (SELECT id FROM companies WHERE name = 'Feline Rescue, Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('President', '', 'kate.king@felinerescue.org', (SELECT id FROM companies WHERE name = 'Feline Rescue, Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kate', 'Burgraff', 'kateburggraff@ffen.org', (SELECT id FROM companies WHERE name = 'Foundations for Essential Needs' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jill', 'Hughes', 'director@finfood.org', (SELECT id FROM companies WHERE name = 'Friends in Need Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Rita', 'Thofern', 'rthofern@willowkinnifriends.org', (SELECT id FROM companies WHERE name = 'Friends of Willow River and Kinnickinnic State Parks' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Rachel', 'Lehman', 'rachel.lehman@greatexpectationsschool.org', (SELECT id FROM companies WHERE name = 'Great Expectations School' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Tea', '', 'Aaliyah@GreenCardVoices.org', (SELECT id FROM companies WHERE name = 'Green Card Voices' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Aaliyah', 'Hannah', 'Aaliyah@GreenCardVoices.org', (SELECT id FROM companies WHERE name = 'Green Card Voices' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Doug', 'Niemala', 'Doug@H2OforLifeSchools.org', (SELECT id FROM companies WHERE name = 'H2O For Life' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Phia', 'Xiong', 'phia.xiong@handyhelpllc.com', (SELECT id FROM companies WHERE name = 'Handy Help LLC' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jenna', 'Lebert', NULL, (SELECT id FROM companies WHERE name = 'Haven House' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', NULL, (SELECT id FROM companies WHERE name = 'Haven House' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Diana', 'Hawkins', 'dhawkins@hncmpls.org', (SELECT id FROM companies WHERE name = 'Hawthorne Neighborhood Council' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'dhawkins@hncmpls.org', (SELECT id FROM companies WHERE name = 'Hawthorne Neighborhood Council' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Rob', 'Thomas', 'Kmueller@HistoryTheatre.com', (SELECT id FROM companies WHERE name = 'History Theatre' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Karen', 'Mueller', 'Kmueller@HistoryTheatre.com', (SELECT id FROM companies WHERE name = 'History Theatre' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Managing', 'Director', 'Kmueller@HistoryTheatre.com', (SELECT id FROM companies WHERE name = 'History Theatre' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Txong', 'Pao Lee', 'txong@hmongcc.org', (SELECT id FROM companies WHERE name = 'Hmong Cultural Center' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'txong@hmongcc.org', (SELECT id FROM companies WHERE name = 'Hmong Cultural Center' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('LaChelle', 'Williams', 'lwilliams@hope4youthmn.org', (SELECT id FROM companies WHERE name = 'HOPE 4 Youth' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'lwilliams@hope4youthmn.org', (SELECT id FROM companies WHERE name = 'HOPE 4 Youth' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sara', 'Kern', 'info@hope-coalition.org', (SELECT id FROM companies WHERE name = 'HOPE Coalition' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'info@hope-coalition.org', (SELECT id FROM companies WHERE name = 'HOPE Coalition' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Dan', 'Pfarr', 'dan.pfarr@180degreed.org', (SELECT id FROM companies WHERE name = 'Hope House' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('President', '', 'dan.pfarr@180degreed.org', (SELECT id FROM companies WHERE name = 'Hope House' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('CEO', '', 'dan.pfarr@180degreed.org', (SELECT id FROM companies WHERE name = 'Hope House' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Dan', 'Pfar', 'Dan@ICAFoodShelf.org', (SELECT id FROM companies WHERE name = 'ICA Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kevin', 'Ward', 'executivedirector@iocp.org', (SELECT id FROM companies WHERE name = 'Interfaith Outreach & Community Partners' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Directir', 'executivedirector@iocp.org', (SELECT id FROM companies WHERE name = 'Interfaith Outreach & Community Partners' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sarah', 'Vansickle', 'info@irishfair.com', (SELECT id FROM companies WHERE name = 'Irish Fair of Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Event', 'Manager', 'info@irishfair.com', (SELECT id FROM companies WHERE name = 'Irish Fair of Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Judy', 'Halper', 'jhalper@jfcsmpls.org', (SELECT id FROM companies WHERE name = 'Jewish Family and Children''s Services' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('CEO', '', 'jhalper@jfcsmpls.org', (SELECT id FROM companies WHERE name = 'Jewish Family and Children''s Services' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Marvin', 'Liszt', 'info@j-hap.org', (SELECT id FROM companies WHERE name = 'Jewish Programming and Housing (J-HAP)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Board', 'President', 'info@j-hap.org', (SELECT id FROM companies WHERE name = 'Jewish Programming and Housing (J-HAP)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Leah', 'Patton', 'leah@jrlc.org', (SELECT id FROM companies WHERE name = 'Joint Religious Legislative Coalition' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Darby', 'Lunceford', 'office@lakeshoreplayers.org', (SELECT id FROM companies WHERE name = 'Lakeshore Payers' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Martha', 'Moriarity', 'mm@ldaminnesota.org', (SELECT id FROM companies WHERE name = 'LDA Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jen', 'Lee', 'jlee@legalassist.org', (SELECT id FROM companies WHERE name = 'Legal Services of North Dakota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jordan', 'Lee Thompson', 'contact@listenupyouthradio.org', (SELECT id FROM companies WHERE name = 'Listen Up Youth Radio' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Anton', 'Jones', 'RaviKrishnan93@gmail.com', (SELECT id FROM companies WHERE name = 'Literacy Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Susan', 'Goodin', 'RaviKrishnan93@gmail.com', (SELECT id FROM companies WHERE name = 'Literacy Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('James', 'Falvey', 'jfalvey@friendsco.org', (SELECT id FROM companies WHERE name = 'Friends & Co' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Daniel', 'Gumnit', 'dgumnit@littlefreelibrary.org', (SELECT id FROM companies WHERE name = 'Little Free Library' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Al', 'Norby', 'anorby@loveinccc.org', (SELECT id FROM companies WHERE name = 'Love Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Stacy', 'Lung', 'licdirector@islandcamp.org', (SELECT id FROM companies WHERE name = 'Lutheran Island Camp' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Steve', 'Houtz', 'steven.houtz@macc-mn.org', (SELECT id FROM companies WHERE name = 'Metropolitan Alliance of Connected Communities (MACC)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('CEO', '', 'steven.houtz@macc-mn.org', (SELECT id FROM companies WHERE name = 'Metropolitan Alliance of Connected Communities (MACC)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Forrest', '', 'ngregory@youthwayministries.org', (SELECT id FROM companies WHERE name = 'Manna Market' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Nancy', 'Gregory', 'ngregory@youthwayministries.org', (SELECT id FROM companies WHERE name = 'Manna Market' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jesse', 'Bethke-Gomez', 'jessebg@mcil-mn.org', (SELECT id FROM companies WHERE name = 'Metropolitan Center for Independent Living (MCIL)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Carrie', 'Opheim', NULL, (SELECT id FROM companies WHERE name = 'McLeod Emergency Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sherry', 'Wichitchu', 'sherry@melsa.org', (SELECT id FROM companies WHERE name = 'MELSA' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Dan', 'Rodriguez', 'drodriguez@merrickcs.org', (SELECT id FROM companies WHERE name = 'Merrick Community Services' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sara', 'Patrick', 'Sara.Patrick@mro.net', (SELECT id FROM companies WHERE name = 'Midwest Reliability Organization' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Julie', 'Johnson', 'jjohnson@mssmn.org', (SELECT id FROM companies WHERE name = 'Midwest Special Services' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jeremy', 'Schreifels', 'jshreifels@milestone.org', (SELECT id FROM companies WHERE name = 'Milestone' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ashley', 'Nathe', 'MplsFarmersMarket@gmail.com', (SELECT id FROM companies WHERE name = 'Minneapolis Farmers Market' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ann', 'Mavity', 'anne.mavity@mhponline.org', (SELECT id FROM companies WHERE name = 'Minnesota Housing Partnership (MHP)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jennifer', 'Fink', 'Jennifer.Fink@newbrightonmn.gov', (SELECT id FROM companies WHERE name = 'Minnesota Parks and Recreation Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ron', 'Busby Sr.', 'info@minnesotablackchamber.org', (SELECT id FROM companies WHERE name = 'MN Black Chamber of Commerce' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Romi', 'Slowiak', 'RomiSlowiak@gmail.com', (SELECT id FROM companies WHERE name = 'MN China Friendship Garden Society' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Bill', 'Zajicek', 'RomiSlowiak@gmail.com', (SELECT id FROM companies WHERE name = 'MN China Friendship Garden Society' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Matt', 'Dickhausen', 'mdickhausen@mn-mcea.org', (SELECT id FROM companies WHERE name = 'MN Community Education Association' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Anne', 'Gainey', 'ATGainey@gmail.com', (SELECT id FROM companies WHERE name = 'MN Community Health Workers Alliance' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kathy', 'Messerli', 'kmesserli@mnhomecare.org', (SELECT id FROM companies WHERE name = 'MN HomeCare Association' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Allen', 'Stauffer', 'al@tcgateway.com', (SELECT id FROM companies WHERE name = 'MN Metro North Tourism' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Travis', 'Smith', 'info@msboa.org', (SELECT id FROM companies WHERE name = 'MN School Bus Operators Association' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('S', '', 'sandy@msfca.org', (SELECT id FROM companies WHERE name = 'MN State Fire Chiefs Association' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('y', 'Schueller', 'sandy@msfca.org', (SELECT id FROM companies WHERE name = 'MN State Fire Chiefs Association' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Noah', 'Swiler', 'amy@mski.org', (SELECT id FROM companies WHERE name = 'MN Youth Ski League' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Board', 'Member', 'amy@mski.org', (SELECT id FROM companies WHERE name = 'MN Youth Ski League' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Amy', 'Cichanowski', 'amy@mski.org', (SELECT id FROM companies WHERE name = 'MN Youth Ski League' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'amy@mski.org', (SELECT id FROM companies WHERE name = 'MN Youth Ski League' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jason', 'Swanson', 'Jswanson@MNRAAA.org', (SELECT id FROM companies WHERE name = 'MNRAAA' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Angela', 'Gauthier', 'email@movefwd.org', (SELECT id FROM companies WHERE name = 'MoveFwd Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jen', 'Wothe', 'info@msamn.com', (SELECT id FROM companies WHERE name = 'MN Subcontractors Association' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Deidre', 'Lynch Nicholson', 'dnichol-son@naehcy.org', (SELECT id FROM companies WHERE name = 'NAEHCY' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Karen', 'Goodenough', 'kgoodenough@socialworkers.org', (SELECT id FROM companies WHERE name = 'National Association of Social Workers' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Dawn', 'Wambeke', 'dawn@neighborsmn.org', (SELECT id FROM companies WHERE name = 'Neighbors, Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kathi', 'Kirchoff', 'nspfs@gmail.com', (SELECT id FROM companies WHERE name = 'North St. Paul Area Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jennifer', 'Freeburg', 'jennifer.freeburg@NCSIdaysupports.org', (SELECT id FROM companies WHERE name = 'Northeast Contemporary Services, Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jess', 'Nelson', 'jnelson@oasisforyouth.oth', (SELECT id FROM companies WHERE name = 'Oasis for Youth' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Tricia', 'Wright', 'tricia@onwardep.org', (SELECT id FROM companies WHERE name = 'Onward Eden Prairie' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jessica', 'Francis', 'jessica@opencupboard.org', (SELECT id FROM companies WHERE name = 'Open Cupboard' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Cindy', 'Ley', 'cindyl.opendoors@gmail.com', (SELECT id FROM companies WHERE name = 'Open Doors for Youth' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Shelly', 'Smith', 'shelly.smith@ourneighborsplace.org', (SELECT id FROM companies WHERE name = 'Our Neighbor''s Place' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Mike', 'Miner', 'mminer@paimn.org', (SELECT id FROM companies WHERE name = 'Phoenix Alternative, Inc.(PAI)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Julie', 'Zbaracki', NULL, (SELECT id FROM companies WHERE name = 'Partnership Resources, Inc.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Peter', 'Schuna - Debby Schuna', 'consult@pathwayhealth.com', (SELECT id FROM companies WHERE name = 'Pathway Health Services' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Darlene', 'Scott', 'dscott@phoenixresidence.org', (SELECT id FROM companies WHERE name = 'Phoenix Residence' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Veronica', 'Crosier', 'veronicac@PSAI.org', (SELECT id FROM companies WHERE name = 'Portable Sanitation Association International' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Pete', 'Steinke', 'paul@preservationalliance.com', (SELECT id FROM companies WHERE name = 'Preservation Alliance' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Michelle', 'Ness', 'mness@prismmpls.org', (SELECT id FROM companies WHERE name = 'PRISM' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Katie', 'Holmgren', 'kholgren@projectpathfinder.org', (SELECT id FROM companies WHERE name = 'Project Pathfinder' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Mohannad', 'Ghawanmeh', 'mohannad@publicartsstpaul.org', (SELECT id FROM companies WHERE name = 'Public Arts St. Paul' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Michelle', 'Belitz', 'michelle.belitz@CO.RAMSEY.MN.US', (SELECT id FROM companies WHERE name = 'Ramsey County Workforce Solutions' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Joan', 'Twiton', 'jtwiton@relatemn.org', (SELECT id FROM companies WHERE name = 'Relate Counseling Center' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Tracie', 'Stanton', 'tracie@resourcewest.org', (SELECT id FROM companies WHERE name = 'Resource West' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Craig', 'Moriak', 'Moriak.Ent@gmail.com', (SELECT id FROM companies WHERE name = 'Ridgeview Senior Apartments' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Marc', 'Morrison', 'info@rreal.org', (SELECT id FROM companies WHERE name = 'Rural Renewable Energy Alliance (RREAL)' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Tabitha', 'Montgomery', NULL, (SELECT id FROM companies WHERE name = 'Seward Community Co-Op' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Cherie', 'Matson', 'sibleycountyfoodshare@gmail.com, sv1cm2mattson@gmail.com', (SELECT id FROM companies WHERE name = 'Sibley County FoodShare' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Diamond', 'Hunter', 'Dhunter@solidgroundmn.org', (SELECT id FROM companies WHERE name = 'Solid Ground' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sara', 'Meeks', 'Dhunter@solidgroundmn.org', (SELECT id FROM companies WHERE name = 'Solid Ground' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Laurie', 'Brownelkl', 'laurie@semaaa.org', (SELECT id FROM companies WHERE name = 'Southeast Minnesota Area Agency on Aging' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Josh', 'Munsch', 'josh@southsideservices.org', (SELECT id FROM companies WHERE name = 'Southside Services I. INC.' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Kara', 'Schommer', 'kara.schommer@gmail.com', (SELECT id FROM companies WHERE name = 'St. Paul Community Literacy Consortium' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Mary', 'Larew', 'mary@thespcm.org', (SELECT id FROM companies WHERE name = 'St. Paul Conservatory of Music' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Nina', 'Archabal', 'mary@thespcm.org', (SELECT id FROM companies WHERE name = 'St. Paul Conservatory of Music' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Deborah', 'Moses', 'Kyle.Hanson@agatemn.org', (SELECT id FROM companies WHERE name = 'Agate Housing and Services' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Carrie', 'Zelin Johnson', NULL, (SELECT id FROM companies WHERE name = 'Start Early Funders Coalition' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Tracy', 'Keibler', 'tracy@startseniorsolutions.org', (SELECT id FROM companies WHERE name = 'START Senior Solutions' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Alicia', 'Hause', 'ahouse@rummlerHOPE.org', (SELECT id FROM companies WHERE name = 'Steve Rummler Hope Network' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Elsbeth', 'Howe', 'splf@stillwaterlibraryfoundation.org', (SELECT id FROM companies WHERE name = 'Stillwater Public Library Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Okpara', 'Rice', 'orice@tanagerplace.org', (SELECT id FROM companies WHERE name = 'Tanager Place' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Dawn', 'Simonsen', 'dsimonsen@trellisconnects.org', (SELECT id FROM companies WHERE name = 'Trellis' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Trevor', 'B Johnson', 'info@tasksunlimited.org', (SELECT id FROM companies WHERE name = 'Tasks Unlimited' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Ross', 'Dunbar', 'isthmusfoundation.org', (SELECT id FROM companies WHERE name = 'The Isthmus Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('James', 'Dutton', 'isthmusfoundation.org', (SELECT id FROM companies WHERE name = 'The Isthmus Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Cathy', 'H', 'cathy@theliftgarage.org', (SELECT id FROM companies WHERE name = 'The Lift Garage' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Beth', 'Holger', 'bholger@thelinkmn.org', (SELECT id FROM companies WHERE name = 'The Link' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Rick', 'Robbins', 'robbinsr@partnershipplan.org', (SELECT id FROM companies WHERE name = 'The Partnership Plan' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Br', '', 'brandon@theperiphery.com', (SELECT id FROM companies WHERE name = 'The Periphery Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('on', 'Ferdig', 'brandon@theperiphery.com', (SELECT id FROM companies WHERE name = 'The Periphery Foundation' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Cisa', 'Keller', 'info@thinksmall.org', (SELECT id FROM companies WHERE name = 'Think Small' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('MJ', 'Carpio', 'mjc@movemn.org', (SELECT id FROM companies WHERE name = 'Move Minnesota' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Christina', 'Miller', 'christina@mathrecovery.org', (SELECT id FROM companies WHERE name = 'US Math Recovery Council' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Jonna', 'Phillips', 'jonna@veteranresilience.org', (SELECT id FROM companies WHERE name = 'Veteran Resilience Project' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Sara', 'Hanson', 'office@whitebearhistory.org', (SELECT id FROM companies WHERE name = 'White Bear Lake Area Historical Society' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'office@whitebearhistory.org', (SELECT id FROM companies WHERE name = 'White Bear Lake Area Historical Society' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Rich', 'Melzer', 'rmelzer@youthlinkmn.org', (SELECT id FROM companies WHERE name = 'YouthLink' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Chief', 'Executive Officer', 'rmelzer@youthlinkmn.org', (SELECT id FROM companies WHERE name = 'YouthLink' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Perry', 'Peterson', 'perry@whitebearfoodshelf.org', (SELECT id FROM companies WHERE name = 'White Bear Area Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW()),
('Executive', 'Director', 'perry@whitebearfoodshelf.org', (SELECT id FROM companies WHERE name = 'White Bear Area Food Shelf' AND organization_id = {ORG_ID} LIMIT 1), {ORG_ID}, {USER_ID}, NOW(), NOW());

-- Verify contacts were inserted
SELECT COUNT(*) as contact_count 
FROM contacts 
WHERE organization_id = {{ORG_ID}};

-- Show sample of inserted contacts with their companies
SELECT 
    c.first_name,
    c.last_name,
    c.email,
    comp.name as company_name
FROM contacts c
LEFT JOIN companies comp ON c.company_id = comp.id
WHERE c.organization_id = {{ORG_ID}}
ORDER BY c.created_at DESC
LIMIT 10;
