-- Insert Companies (run this first)
INSERT INTO companies (
    name, street_address, city, state, postal_code, website, description, status,
    organization_id, created_at, updated_at
) VALUES
('Advocating Change Together (ACT)', '1821 University Ave W S177', 'St. Paul', 'MN', '55104', NULL, 'Jen Walton is the new Executive Director', 'Active', 7, NOW(), NOW()),
('American Indian Family Center', '579 Wells St', 'St. Paul', 'MN', '55130', NULL, '6/5/25 Submitting Proposal for Search', 'Active', 7, NOW(), NOW()),
('American Association of Woodturners', 'Landmark Center', 'St. Paul', 'MN', '55102', NULL, 'ED just left', 'Active', 7, NOW(), NOW()),
('American Indian OIC', '1845 E Franklin Ave', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Ampersand Families', '1751 County Rd B West, Ste 300', 'Roseville', 'MN', '55113', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Annex Teen Clinic', '5810 N 42nd Ave', 'Robbinsdale', 'MN', '55422', NULL, 'old', 'Active', 7, NOW(), NOW()),
('Aqwalife', '1 Four Coins Drive', 'Canonsburg', 'PA', '15317', NULL, 'old', 'Active', 7, NOW(), NOW()),
('Arcola Mills', 'PO Box 313', 'Stillwater', 'MN', '55082', NULL, 'Google has noted it is temporarily closed. Cecily: Actually they tried to recruit me for the Board. They are coming back after issues with May Township', 'Active', 7, NOW(), NOW()),
('Ausherman Family Foundation', '7420 Hayward Rd #203', 'Frederick', 'MD', '21702', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Avenues for Youth', '1708 Oakland Park Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', 7, NOW(), NOW()),
('The Beacon', '1717 Woodland Ave', 'Des Moines', 'MN', '50309', NULL, 'Note - I just did a Google Search and found an article in the Des Moines Busines Journal from September 2024 announcing the search for a new ED. I''ll reach out to see if I can find out who the new contact is.', 'Active', 7, NOW(), NOW()),
('Belle Plaine Food Shelf', '128 N Meridian St', 'Belle Plaine', 'MN', '56011', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Bellis', '2038 Ford Pkwy, PMB 457', 'St Paul', 'MN', '55116', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Beyond New Beginnings', '5666 Lincoln Dr Ste 210', 'Edina', 'MN', '55436', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Big Lake Community Food Shelf', '160 Lake St N', 'Big Lake', 'MN', '55309', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Breakthrough Twin Cities', '2051 Larpenteur Ave E', 'St. Paul', 'MN', '55109', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Bridge for Youth', '1111 W 22nd St', 'Minneapolis', 'MN', '55405', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Bridges of Hope', '2011 S 6th St', 'Brainerd', 'MN', '56401', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('CADA', NULL, NULL, NULL, NULL, NULL, 'I see on linked in that their previous ED whom I worked with is no longer with the org.', 'Active', 7, NOW(), NOW()),
('CAER Food Shelf', '12621 Elk Lake Rd NW', 'Elk River', 'MN', '55330', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Camp Omega', '22750 Lind Ave', 'Waterville', 'MN', '56096', NULL, NULL, 'Active', 7, NOW(), NOW()),
('CAPI', '5930 Brooklyn Blvd', 'Minneapolis', 'MN', '55429', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Carver County Historical Society', '555 W 1st St', 'Waconia', 'MN', '55387', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Communnity Emergency Assistance Program (CEAP)', '7051 Brooklyn Blvd', 'Brooklyn Center', 'MN', '55429', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Center for Coaching in Organizations', '8216 W 102nd St', 'Bloomington', 'MN', '55438', NULL, 'Proposal in 2024 - Declined', 'Active', 7, NOW(), NOW()),
('Central Minnesota Mental Health Center', '411 3rd St N', 'Waite Park', 'MN', '56387', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Century College Foundation', 'East Campus, E2507', 'White Bear Lake', 'MN', '55110', NULL, 'NOTE: NORA REQUESTED TO NO LONGER RECEIVE EMAILS FROM US 7.1.2025
ED is retiring this spring . Cecily: I know Nora Slawik from SACF, Is this retiring?', 'Active', 7, NOW(), NOW()),
('Child Care Aware', '10 River Park Plaza #820', 'St. Paul', 'MN', '55107', NULL, 'ED retired in May 2025.', 'Active', 7, NOW(), NOW()),
('Children''s Hospital Association', '347 Smith Ave N #501', 'St. Paul', 'MN', '55102', NULL, NULL, 'Active', 7, NOW(), NOW()),
('College Possible', '755 Prior Ave N Ste 200', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', 7, NOW(), NOW()),
('CommonBond Communities', '1080 Montreal Ave', 'St. Paul', 'MN', '55116', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Accord', '1515 Energy Park Dr', 'St. Paul', 'MN', '55108', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('Community Thread', '2300 Orleans St W', 'Stillwater', 'MN', '55082', NULL, 'Sally retired- new ED is Derrick Jaeger. Email retuned as undeliverable.', 'Active', 7, NOW(), NOW()),
('Conservation Corps Minnesota and Iowa', '60 Plato Blvd', 'St. Paul', 'MN', '55107', NULL, 'I know Haley Nelson, their recruitment manager. We were on the FFEN Bd together- Andrea', 'Active', 7, NOW(), NOW()),
('Corner House', '2502 10th Ave S', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Customized Options', '7447 4th St N', 'Oakdale', 'MN', '55128', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Dakota Woodlands', '3430 Wescott Woodlands', 'Eagan', 'MN', '55123', NULL, 'Jennifer Harrison has left, but I see on Linked In that JoHana Smrcina who I worked with at the Lift Garage is now their Director of Housing. Ceily: Added ED', 'Active', 7, NOW(), NOW()),
('DARTS', '1645 Marthaler Ln', 'West St. Paul', 'MN', '55118', NULL, NULL, 'Active', 7, NOW(), NOW()),
('DepartSmart', '5775 Wayzata Blvd #700', 'St. Louis Park', 'MN', '55416', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Dispute Resolution Center', '844 Selby Ave', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', 7, NOW(), NOW()),
('DuNord Foundation', '2610 E 32nd St', 'Minneapolis', 'MN', '55406', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Emerge', '1834 Emerson Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Epilepsy Foundation of Minnesota', '7760 France Ave S Ste 210', 'Bloomington', 'MN', '55435', NULL, NULL, 'Active', 7, NOW(), NOW()),
('EVOLVE Family Services', '5850 Omaha Ave N', 'Stillwater', 'MN', '55082', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Face 2 Face', '1165 Arcade St', 'St. Paul', 'MN', '55106', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Family Child Development Center', '100 Nathan Lane N', 'Minneapolis', 'MN', '55441', NULL, 'No email in contract. Her testimonial on SCC website', 'Active', 7, NOW(), NOW()),
('Feed Iowa First', '1506 10th St SE', 'Cedar Rapids', 'IA', '52401', NULL, 'I think this was Emily. New ED in 2024', 'Active', 7, NOW(), NOW()),
('Feline Rescue, Inc.', '593 Fairview Ave N', 'St. Paul', 'MN', '55104', NULL, 'Met with Kate King recently. FR is doing great under her leadership, staff has increased, new board members, Completed an internal strategic planning process.', 'Active', 7, NOW(), NOW()),
('Financial One Credit Union', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', 7, NOW(), NOW()),
('Foundations for Essential Needs', '701 N 3rd ST #203', 'Minneapolis', 'MN', '55401', NULL, 'I was on their board and am close friend with Kate Burgraff. My duaghter babysits for her boys - Andrea', 'Active', 7, NOW(), NOW()),
('Friends in Need Food Shelf', '535 4th St', 'St. Paul Park', 'MN', '55071', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Friends of St. Paul College Foundation', '235 Marshall Ave', 'St. Paul', 'MN', '55102', 'https://www.saintpaul.edu/alumni/friends/#about', NULL, 'Active', 7, NOW(), NOW()),
('Friends of Willow River and Kinnickinnic State Parks', '1034 County Road A', 'Hudson', 'WI', '54016', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Great Expectations School', '550 5th St', 'Grand Marais', 'MN', '55604', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('Green Card Voices', '2611 1st Ave S', 'Minneapolis', 'MN', '55408', NULL, NULL, 'Active', 7, NOW(), NOW()),
('H2O For Life', '4756 Banning Ave #207', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Handy Help LLC', '2365 McKnight Rd N', 'Maplewood', 'MN', '55109', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Haven House', '1803 Bryant Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Hawkinson Fund for Peace and Justice', '324 Harvard St SE', 'Minneapolis', 'MN', '55414', 'https://www.unitedseminary.edu/lcsj/hawkinsonfund/', 'The Hawkinson Fund for Peace and Justice has moved to the Leadership Center for Social Justice at United Theological Seminary of the Twin Cities', 'Active', 7, NOW(), NOW()),
('Hawthorne Neighborhood Council', '2944 Emerson Ave N', 'Minneapolis', 'MN', '55411', NULL, NULL, 'Active', 7, NOW(), NOW()),
('History Theatre', '30 10th St E', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Hmong Cultural Center', '375 University Ave W #204', 'St. Paul', 'MN', '55103', NULL, NULL, 'Active', 7, NOW(), NOW()),
('HOPE 4 Youth', '10250 Foley Blvd NW #48010', 'Coon Rapids', 'MN', '55448', NULL, 'I used to work there as the VP of Advancement. Still close with NIkki Shapiro their Dir of Advancement- Andrea', 'Active', 7, NOW(), NOW()),
('HOPE Coalition', '1926 Old W Main St Ste 104', 'Red Wing', 'MN', '55066', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Hope House', '3010 W 78th St', 'Excelsior', 'MN', '55331', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('ICA Food Shelf', '11588 K-Tel Dr', 'Minnetonka', 'MN', '55343', NULL, 'Ex Dir is Dan Narr- I worked with him many moons ago at Catholic Charities - Andrea', 'Active', 7, NOW(), NOW()),
('Interfaith Outreach & Community Partners', '1605 County Rd 101', 'Plymouth', 'MN', '55447', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Irish Fair of Minnesota', '836 Prior Ave N Ste 500', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Jewish Family and Children''s Services', '5905 Golden Valley Rd', 'Golden Valley', 'MN', '55422', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Jewish Programming and Housing (J-HAP)', '9280 Golden Valley Rd #140', 'Golden Valley', 'MN', '55427', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Joint Religious Legislative Coalition', '122 W Franklin Ave', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Joyce Uptown Food Shelf', '3041 Fremont Ave S', 'Minneapolis', 'MN', '55408', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Lakeshore Payers', '4941 Long Ave', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', 7, NOW(), NOW()),
('LDA Minnesota', '5101 Olson Memorial Hwy Ste 6000', 'Minneapolis', 'MN', '55422', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Legal Services of North Dakota', '418 E Broadway Ste 25', 'Bismarck', 'ND', '58501', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Listen Up Youth Radio', '550 Vandalia St Ste 170', 'St. Paul', 'MN', '55114', NULL, 'Emily Krumberger was our contact at the time of Emily Z''s departure', 'Active', 7, NOW(), NOW()),
('Literacy Minnesota', '700 Raymond Ave #180', 'St. Paul', 'MN', '55114', NULL, 'Ravi is past board chair', 'Active', 7, NOW(), NOW()),
('Friends & Co', '2550 University Ave W Ste 260-S', 'St. Paul', 'MN', '55114', NULL, 'Formerly Little Brothers Friends of the Elderly', 'Active', 7, NOW(), NOW()),
('Little Earth', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', 7, NOW(), NOW()),
('Little Free Library', '2327 Wycliff St Ste 220', 'St. Paul', 'MN', '55114', NULL, 'Greig Meitzer retiring this summer, ED is now Daniel Gumnit', 'Active', 7, NOW(), NOW()),
('Love Inc.', '1600 Bavaria Rd', 'Chaska', 'MN', '55318', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Lutheran Island Camp', '45011 230th St', 'Henning', 'MN', '56551', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Metropolitan Alliance of Connected Communities (MACC)', '3433 Broadway St NE Ste 230', 'Minneapolis', 'MN', '55413', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Manna Market', '3301 92nd Ave NE', 'Blaine', 'MN', '55449', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Metropolitan Center for Independent Living (MCIL)', '530 Robert St N', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', 7, NOW(), NOW()),
('McLeod Emergency Food Shelf', '719 13th St E', 'Glencoe', 'MN', '55336', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MDE', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', 7, NOW(), NOW()),
('Meeker County Emergency Food Shelf', '118 N Sibley Ave', 'Litchfield', 'MN', '55355', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('MELSA', '1619 W Dayton Ave #314', 'St. Paul', 'MN', '55104', NULL, 'New ED with solid skills. Changes with State budget have not yet impacted MELSA. However, concerns about libraries across Minnesota.', 'Active', 7, NOW(), NOW()),
('Merrick Community Services', '1669 Arcade St Ste 4', 'St. Paul', 'MN', '55106', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Midwest Reliability Organization', '380 St Peter St #800', 'St. Paul', 'MN', '55102', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Midwest Special Services', '900 Ocean St', 'St. Paul', 'MN', '55106', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Milestone', '1821 University Ave W S 164', 'St. Paul', 'MN', '55104', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('Minneapolis Farmers Market', '312 E Lyndale Ave N', 'Minneapolis', 'MN', '55405', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Minnesota Housing Partnership (MHP)', '2446 University Ave W #106', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Minnesota Parks and Recreation Foundation', '200 Charles St NE', 'Fridley', 'MN', '55432', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN Black Chamber of Commerce', '401 Robert St N #150', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN China Friendship Garden Society', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN Community Education Association', '13750 Lake Blvd', 'Lindstrom', 'MN', '55045', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN Community Health Workers Alliance', '2250 University Ave W Ste 200N', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN HomeCare Association', '1265 Grey Fox Rd Ste 2', 'Arden Hills', 'MN', '55112', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN Metro North Tourism', '7071 University Ave NE', 'Fridley', 'MN', '55432', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN School Bus Operators Association', '1611 County B Rd W', 'St. Paul', 'MN', '55113', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('MN State Community and Technical College Foundation', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN State Fire Chiefs Association', '1433 Idaho Ave W', 'St. Paul', 'MN', '55108', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MN Youth Ski League', 'PO Box 18659', 'Minneapolis', 'MN', '55418', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('MNRAAA', '201 North Broad St Ste 102', 'Mankato', 'MN', '56001', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Minnesota Organization for Habilitation and Rehabilitation(MOHR)', '2027 Rice St', 'Roseville', 'MN', '55113', NULL, NULL, 'Active', 7, NOW(), NOW()),
('MoveFwd Minnesota', '1001 MN-7 #237', 'Hopkins', 'MN', '55305', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('MN Subcontractors Association', '4248 Park Glen Rd', 'Minneapolis', 'MN', '55416', NULL, NULL, 'Active', 7, NOW(), NOW()),
('NAEHCY', '13570 Grove Drive #302', 'Maple Grove', 'MN', '55311', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('National Association of Social Workers', 'PO Box 92', 'Backus', 'MN', '56435', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('Neighbors, Inc.', '222 Grand Ave W', 'South St. Paul', 'MN', '55075', NULL, NULL, 'Active', 7, NOW(), NOW()),
('North St. Paul Area Food Shelf', '2266 2nd St N', 'St. Paul', 'MN', '55109', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('Northeast Contemporary Services, Inc.', '2782 Cleveland Ave N', 'Roseville', 'MN', '55113', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Oasis for Youth', '2200 W Old Shakopee Rd', 'Bloomington', 'MN', '55431', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Onward Eden Prairie', 'PO Box 44863', 'Eden Prairie', 'MN', '55344', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Open Cupboard', '8264 4th St N', 'Oakdale', 'MN', '55128', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Open Doors for Youth', '554 3rd St NW Ste 201', 'Elk River', 'MN', '55330', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Our Neighbor''s Place', '122 W Johnson St', 'River Falls', 'WI', '54022', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Phoenix Alternative, Inc.(PAI)', '3700 Highway 61 N Ste 200', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Partnership Resources, Inc.', '1069 10th Ave SE', 'Minneapolis', 'MN', '55414', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Pathway Health Services', '11240 Stillwater Blvd', 'Lake Elmo', 'MN', '55042', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Phoenix Residence', '222 Plato Blvd', 'St. Paul', 'MN', '55107', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Portable Sanitation Association International', '1601 Utica Ave S Ste 213', 'Minneapolis', 'MN', '55416', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Preservation Alliance', 'Landmark Center', 'St. Paul', 'MN', '55102', NULL, NULL, 'Active', 7, NOW(), NOW()),
('PRISM', '1220 Zane Ave N', 'Golden Valley', 'MN', '55422', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Project Pathfinder', '570 N Asbury St #300', 'St. Paul', 'MN', '55104', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('Public Arts St. Paul', '370 Wabasha St N Ste 114', 'St. Paul', 'MN', '55102', NULL, 'Email returned as undeliverable
The people that i worked with are gone now, but we could reach out.', 'Active', 7, NOW(), NOW()),
('Ramsey County Workforce Solutions', '121 7th Pl E #2100', 'St. Paul', 'MN', '55101', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Ampact', '2400 Park Ave', 'Minneapolis', 'MN', '55404', NULL, 'Formerly Reading & Math, Inc', 'Active', 7, NOW(), NOW()),
('Relate Counseling Center', '5125 County Rd 101', 'Minnetonka', 'MN', '55345', NULL, NULL, 'Active', 7, NOW(), NOW()),
('RESOURCE', '1900 Chicago Ave S', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Resource West', '1011 1st St S', 'Hopkins', 'MN', '55343', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Ridgeview Senior Apartments', '390 5th St NW #108', 'Clear Lake', 'MN', '54005', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Rural Renewable Energy Alliance (RREAL)', '3963 8th St SW', 'Backus', 'MN', '56435', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Seward Community Co-Op', '2823 E Franklin Ave', 'Minneapolis', 'MN', '55406', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Sibley County FoodShare', '111 Industrial Ave S', 'Gaylord', 'MN', '55334', NULL, NULL, 'Active', 7, NOW(), NOW()),
('SOAR Regional Arts', 'PO Box 372', 'St. Michael', 'MN', '55376', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Solid Ground', '3521 Century Ave N', 'White Bear Lake', 'MN', '55110', NULL, 'I worked here as Dir of Advancement - Andrea', 'Active', 7, NOW(), NOW()),
('Som Gum Cooperative', '5010 Washington St NE', 'Minneapolis', 'MN', '55421', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Somerset Community Food Pantry', 'PO Box 297', 'Somerset', 'WI', '54025', NULL, 'This was Heidi, Cecily can try to reach out to them if desired', 'Active', 7, NOW(), NOW()),
('Southeast Minnesota Area Agency on Aging', '2720 Superior Dr NW #102', 'Rochester', 'MN', '55901', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Southside Services I. INC.', '1845 E Lake St #200', 'Minneapolis', 'MN', '55407', NULL, NULL, 'Active', 7, NOW(), NOW()),
('St. Paul Community Literacy Consortium', '700 Raymond Ave #180', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', 7, NOW(), NOW()),
('St. Paul Conservatory of Music', '1619 Dayton Ave Ste 200', 'St. Paul', 'MN', '55104', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Agate Housing and Services', '2309 Nicollet Ave', 'Minneapolis', 'MN', '55404', NULL, 'Current ED is Kyle Hanson Kyle.Hanson@agatemn.org, was St Stephens', 'Active', 7, NOW(), NOW()),
('Start Early Funders Coalition', NULL, NULL, NULL, NULL, NULL, NULL, 'Active', 7, NOW(), NOW()),
('START Senior Solutions', '6995 Mariann Dr', 'Eden Prairie', 'MN', '55346', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Steve Rummler Hope Network', '2233 University Ave W Ste 325', 'St. Paul', 'MN', '55114', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Stillwater Public Library Foundation', '224 North Third St', 'Stillwater', 'MN', '55082', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Tanager Place', '1030 5th Ave SE', 'Cedar Rapids', 'IA', '52403', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Trellis', '1265 Grey Fox Rd Ste 2', 'Arden Hills', 'MN', '55112', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Tasks Unlimited', '2419 Nicollet Ave', 'Minneapolis', 'MN', '55404', NULL, NULL, 'Active', 7, NOW(), NOW()),
('The Annex Teen Clinic', '2748 Lyndale Ave S', 'Minneapolis', 'MN', '55408', NULL, NULL, 'Active', 7, NOW(), NOW()),
('The Isthmus Foundation', '10141 Irwin Rd', 'Minneapolis', 'MN', '55437', NULL, 'Recently spoke with Ross. He reported that they are currently doing well.', 'Active', 7, NOW(), NOW()),
('The Lift Garage', '2401 E Lake St', 'Minneapolis', 'MN', '55406', NULL, 'JoHanna has left.', 'Active', 7, NOW(), NOW()),
('The Link', '1210 Glenwood Ave', 'Minneapolis', 'MN', '55405', NULL, NULL, 'Active', 7, NOW(), NOW()),
('The Partnership Plan', '1875 Greeley St S', 'Stillwater', 'MN', '55082', NULL, 'Cecily: I know their current DD consultant', 'Active', 7, NOW(), NOW()),
('The Periphery Foundation', '5322 Maywood Rd Ste 3', 'Mound', 'MN', '55364', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Think Small', '10 Yorkton Ct', 'St. Paul', 'MN', '55117', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Move Minnesota', '2356 University Ave W', 'St. Paul', 'MN', '55114', NULL, 'Was once Transit for Livable Communities', 'Active', 7, NOW(), NOW()),
('US Math Recovery Council', '510 Lone Oak Rd', 'Eagan', 'MN', '55121', NULL, NULL, 'Active', 7, NOW(), NOW()),
('Veteran Resilience Project', 'PO Box 1057', 'Minnetonka', 'MN', '55345', NULL, 'VRP lost their funding through the state legislature this session between $200 to $400,000 so significant decrease. This will possibly mean layoffs. Currently working with Access Philanthropy.', 'Active', 7, NOW(), NOW()),
('White Bear Lake Area Historical Society', '2228 4th St', 'White Bear Lake', 'MN', '55110', NULL, NULL, 'Active', 7, NOW(), NOW()),
('YouthLink', '41 N 12th St', 'Minneapolis', 'MN', '55403', NULL, 'Email returned as undeliverable', 'Active', 7, NOW(), NOW()),
('White Bear Area Food Shelf', '1884 Whitaker St', 'White Bear Lake', 'MN', '55110', NULL, 'Renae was the interim director that hired me as their Ex Dir many moons ago. I know they need help. - Andrea', 'Active', 7, NOW(), NOW());

-- Check if companies were inserted
SELECT COUNT(*) as company_count FROM companies WHERE organization_id = 7;

-- Check contacts table structure first
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'contacts' 
ORDER BY ordinal_position;